### ISSUE TITLE
ExceptionInInitializerError on failure to read event log

### ISSUE THREAD

**Issue by XakepSDK** [oshi/oshi#1044]
oshi 4.2.0
People getting this exception. No idea how to reproduce.
```
java.lang.ExceptionInInitializerError
    at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:102)
    at oshi.util.Memoizer$1.get(Memoizer.java:84)
    at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:95)
    at launcher.o.j.h(SourceFile:26)
    at launcher.o.j.i(SourceFile:30)
    at launcher.A.a.a(SourceFile:207)
    at launcher.v.e.a(SourceFile:118)
    at dk.xakeps.bootcamp.u.a(SourceFile:241)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
    at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
    at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
    at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: com.sun.jna.platform.win32.Win32Exception: Неизвестный интерфейс. (translated: Unknown interface)
    at com.sun.jna.platform.win32.Advapi32Util$EventLogIterator.<init>(Advapi32Util.java:2496)
    at oshi.software.os.windows.WindowsOperatingSystem.querySystemBootTime(WindowsOperatingSystem.java:646)
    at oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:103)
    ... 13 more
```

**Comment by XakepSDK** [comment]
jna version: `net.java.dev.jna:jna:jar:5.5.0`, `net.java.dev.jna:jna-platform:jar:5.5.0`

**Comment by XakepSDK** [comment]
User sent me NFO file from `msinfo32`, but it's entries are in russian language
[436035a579e46c96.zip](https://github.com/oshi/oshi/files/3840252/436035a579e46c96.zip)

**Comment by dbwiddis** [comment]
I suspect the counter registry code.  Can the user test 4.1.1?

**Comment by XakepSDK** [comment]
Same exception

**Comment by dbwiddis** [comment]
Thanks for that test -- was reading from phone earlier and now on larger screen I see the "caused by" pointing to the Event Log code.  The user's system is unable to open the event log:

Advapi32.INSTANCE.OpenEventLog(serverName, sourceName);

I can work around this in OSHI by catching the exception and using a fallback method for calculating boot time... I'll do that today and expect a 4.2.1 tonight.

**Comment by dbwiddis** [comment]
I suspect this is an internationalization issue in which the event log "System" does not exist, at least by its English name.

**Comment by dbwiddis** [comment]
#1045 should fix this. Can the user test the fix from SNAPSHOT?  If it works I'll release 4.2.1.
