### ISSUE TITLE
Cant compile with OSGi + Maven

### ISSUE THREAD

**Issue by LukasHanusek** [oshi/oshi#1092]
I have an OSGi project, however I cannot compile it with oshi. Latest working oshi version is 4.1.1, versions 4.2+wont compile.

I get this exception during maven build for every single oshi class imported:

`java.lang.ArrayIndexOutOfBoundsException: 18
	at aQute.lib.osgi.Clazz.parseClassFile(Clazz.java:448)
	at aQute.lib.osgi.Clazz.parseClassFile(Clazz.java:369)
	at aQute.lib.osgi.Clazz.parseClassFileWithCollector(Clazz.java:359)
	at aQute.lib.osgi.Clazz.parseClassFile(Clazz.java:349)
	at aQute.lib.osgi.Analyzer.analyzeJar(Analyzer.java:1725)
	at aQute.lib.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:1618)
	at aQute.lib.osgi.Analyzer.analyze(Analyzer.java:124)
	at aQute.lib.osgi.Builder.analyze(Builder.java:306)
	at aQute.lib.osgi.Analyzer.calcManifest(Analyzer.java:301)
	at aQute.lib.osgi.Builder.build(Builder.java:73)
	at org.apache.felix.bundleplugin.BundlePlugin.buildOSGiBundle(BundlePlugin.java:547)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:347)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:264)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:255)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)`

At the end it says this:
Bundle xxx:bundle:1.0-SNAPSHOT : Exception: 18
Bundle xxx:bundle:1.0-SNAPSHOT : Invalid class file: oshi/SystemInfo.class
Bundle xxx:bundle:1.0-SNAPSHOT : Exception: 18
Bundle xxx:bundle:1.0-SNAPSHOT : Invalid class file: oshi/hardware/common/AbstractCentralProcessor.class
Bundle xxx::bundle:1.0-SNAPSHOT : Exception: 18
Bundle xxx:bundle:1.0-SNAPSHOT : Invalid class file: oshi/hardware/common/AbstractComputerSystem.class

Failed to execute goal org.apache.felix:maven-bundle-plugin:2.3.7:bundle (default-bundle) on project xxx: Error(s) found in bundle configuration -> [Help 1]

Any idea why version 4.1.1 works fine but any version above doesnt ?

**Comment by hazendaz** [comment]
You may want to upgrade the bundle plugin to bnd-maven-plugin version.  Or at least to 4.2.1 of what your currently using.  See if that helps.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LukasHanusek** [comment]
Updated to maven-bundle-plugin 3.0.0 and it works with latest OSHi maven release (4.3.0). I tried latest maven bundle plugin but it would requiere me to restructure the entire project because it had conflicts with other things.

Thanks for help.
