### ISSUE TITLE
OSHI-5.0.1: StackOverflow in getDiskStores() 

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#1207]
Hi,

I get the following error with OSHI 5.0.1 when calling hal.getDiskStores():

```
Exception in thread "main" java.lang.StackOverflowError
	at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:304)
	at java.lang.StringCoding.encode(StringCoding.java:344)
	at java.lang.String.getBytes(String.java:918)
	at java.io.UnixFileSystem.checkAccess(Native Method)
	at java.io.File.canRead(File.java:768)
	at oshi.util.FileUtil.readFile(FileUtil.java:84)
	at oshi.util.FileUtil.readFile(FileUtil.java:69)
	at oshi.hardware.platform.linux.LinuxHWDiskStore.readMountsMap(LinuxHWDiskStore.java:219)
	at oshi.hardware.platform.linux.LinuxHWDiskStore.getDisks(LinuxHWDiskStore.java:139)
	at oshi.hardware.platform.linux.LinuxHWDiskStore.getDisks(LinuxHWDiskStore.java:132)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getDiskStores(LinuxHardwareAbstractionLayer.java:75)
```

Best regards, Space

**Comment by Space2Man** [comment]
When enabling debug logging I get a NPE:

```
AsyncLogger error handling event seq=6900, value='org.apache.logging.log4j.core.async.RingBufferLogEvent@6e76a3eb': java.lang.NullPointerException: null
java.lang.NullPointerException
	at org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161)
	at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45)
	at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.StackOverflowError
	at org.apache.logging.log4j.util.StringBuilders.appendSpecificTypes(StringBuilders.java:79)
	at org.apache.logging.log4j.message.ParameterFormatter.appendSpecialTypes(ParameterFormatter.java:463)
	at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:452)
	at org.apache.logging.log4j.message.ParameterFormatter.formatMessage2(ParameterFormatter.java:189)
	at org.apache.logging.log4j.message.ReusableParameterizedMessage.formatTo(ReusableParameterizedMessage.java:329)
	at org.apache.logging.log4j.core.async.RingBufferLogEvent.setMessage(RingBufferLogEvent.java:133)
	at org.apache.logging.log4j.core.async.RingBufferLogEvent.setValues(RingBufferLogEvent.java:104)
	at org.apache.logging.log4j.core.async.RingBufferLogEventTranslator.translateTo(RingBufferLogEventTranslator.java:60)
	at org.apache.logging.log4j.core.async.RingBufferLogEventTranslator.translateTo(RingBufferLogEventTranslator.java:37)
	at com.lmax.disruptor.RingBuffer.translateAndPublish(RingBuffer.java:962)
	at com.lmax.disruptor.RingBuffer.tryPublishEvent(RingBuffer.java:478)
	at org.apache.logging.log4j.core.async.AsyncLoggerDisruptor.tryPublish(AsyncLoggerDisruptor.java:215)
	at org.apache.logging.log4j.core.async.AsyncLogger.publish(AsyncLogger.java:229)
	at org.apache.logging.log4j.core.async.AsyncLogger.logWithThreadLocalTranslator(AsyncLogger.java:225)
	at org.apache.logging.log4j.core.async.AsyncLogger.access$000(AsyncLogger.java:67)
	at org.apache.logging.log4j.core.async.AsyncLogger$1.log(AsyncLogger.java:152)
	at org.apache.logging.log4j.core.async.AsyncLogger.log(AsyncLogger.java:136)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2190)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2144)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2127)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2020)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1891)
	at org.apache.logging.slf4j.Log4jLogger.debug(Log4jLogger.java:124)
	at oshi.util.FileUtil.readFile(FileUtil.java:86)
	at oshi.util.FileUtil.readFile(FileUtil.java:69)
	at oshi.hardware.platform.linux.LinuxHWDiskStore.readMountsMap(LinuxHWDiskStore.java:219)
	at oshi.hardware.platform.linux.LinuxHWDiskStore.getDisks(LinuxHWDiskStore.java:139)
	at oshi.hardware.platform.linux.LinuxHWDiskStore.getDisks(LinuxHWDiskStore.java:132)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getDiskStores(LinuxHardwareAbstractionLayer.java:75)
```

But why is filename NULL?

**Comment by Space2Man** [comment]
Digged a little deeper and found the culprit somehow to be caused by the following Groovy codeline:

`log.debug("Found diskStore {}", new JsonBuilder(diskStore))`

So somehow this causes some kind of recursion ... I will continue debugging

**Comment by Space2Man** [comment]
My guess is this: JsonBuilder tries to walk the tree of the single disks and finds this:

`static java.util.List<HWDiskStore> | getDisks() | Gets the disks on this machine`

So it tries to gather all the data for all disks ... when checking the first on it again tries to fetch "getDisks()" ... and so on.

**Comment by Space2Man** [comment]
Ok, I think this is somehow bad behaviour of JsonBuilder ...

**Comment by dbwiddis** [comment]
Interesting. I had some problems with Jackson's ObjectMapper trying to fetch any method with a `get` on it and running into serialization issues, but it seems like it's smart enough to avoid recursion.  Let me know if there's something i can do to flag this method for JsonBuilder.  You'd think a static method wouldn't recurse...
