### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/jna/platform/mac/IOKitUtil

### ISSUE THREAD

**Issue by gunjanddave** [oshi/oshi#1384]
```
java.lang.NoClassDefFoundError: com/sun/jna/platform/mac/IOKitUtil
	at oshi.hardware.platform.mac.MacBaseboard.queryPlatform(MacBaseboard.java:75)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.hardware.platform.mac.MacBaseboard.getSerialNumber(MacBaseboard.java:66)
	at com.eaton.system.service.LicenseService.generateSystemId(LicenseService.java:186)
	at com.eaton.system.service.LicenseService.getLicenseDetails(LicenseService.java:934)
	at com.eaton.system.service.LicenseService$$FastClassBySpringCGLIB$$2a287fe8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.eaton.util.logging.LoggingAspect.logFlex(LoggingAspect.java:109)
	at com.eaton.util.logging.LoggingAspect.logGeneral(LoggingAspect.java:62)
	at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.eaton.system.service.LicenseService$$EnhancerBySpringCGLIB$$d5f4c2ae.getLicenseDetails(<generated>)
	at com.eaton.system.util.LicenseUtil.validateLicenseVersion(LicenseUtil.java:59)
	at com.eaton.system.startup.ApplicationStartup.SyncWithNewLicenseVersion(ApplicationStartup.java:369)
	at com.eaton.system.startup.ApplicationStartup.onApplicationEvent(ApplicationStartup.java:133)
	at com.eaton.system.startup.ApplicationStartup.onApplicationEvent(ApplicationStartup.java:1)
	at com.eaton.system.startup.ApplicationStartup$$FastClassBySpringCGLIB$$2c7ba0f9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.eaton.util.logging.LoggingAspect.logFlex(LoggingAspect.java:109)
	at com.eaton.util.logging.LoggingAspect.logGeneral(LoggingAspect.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.eaton.system.startup.ApplicationStartup$$EnhancerBySpringCGLIB$$c2bed881.onApplicationEvent(<generated>)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1203)
	at com.eaton.system.ElmsSystemApplication.main(ElmsSystemApplication.java:67)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.mac.IOKitUtil
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 57 more

```

While starting the service facing this issue.

POM.xml
```
		<dependency>
			<groupId>com.github.oshi</groupId>
			<artifactId>oshi-core</artifactId>
			<version>4.6.1</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/net.java.dev.jna/jna-platform -->
		<dependency>
			<groupId>net.java.dev.jna</groupId>
			<artifactId>jna-platform</artifactId>
			<version>5.4.0</version>
		</dependency>
```

**Comment by dbwiddis** [comment]
This is addressed [in the FAQ](https://github.com/oshi/oshi/blob/master/FAQ.md#how-do-i-resolve-jna-noclassdeffound-errors).

You may be using the Spring Boot Starter Parent which depends on [`spring-boot-dependencies`](https://search.maven.org/artifact/org.springframework.boot/spring-boot-dependencies/2.2.4.RELEASE/pom) which imports JNA 4.5.2.  You must override `jna.properties` in your own POM.

**Comment by gunjanddave** [comment]
@dbwiddis Being new to this. Can you please help with this? Hou to override jna.properties in your own POM?

**Comment by dbwiddis** [comment]
Just do
```
<properties>
   <jna.version>5.6.0</jna.version>
</properties>
```

**Comment by gunjanddave** [comment]
@dbwiddis It is resolved.

**Comment by dbwiddis** [comment]
Great news @wilkinsona 

I’ll update the faq.
