### ISSUE TITLE
Failed to read process file: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java (deleted)

### ISSUE THREAD

**Issue by SimunKaracic** [oshi/oshi#1395]
Copied from https://github.com/kamon-io/Kamon/issues/884
Was this fixed by #1155 ? If yes, what version of oshi was this deployed in? We're using oshi `5.2.5`
```
Some months ago, I got a weird error in one of my apps, today, I got the same error in a different one, Kamon is a piece in both projects, I have no idea how something like this could ha occurred but I'm pasting the error just in case someone has any idea on preventing it.

Failed to read process file: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java (deleted)
    at oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:284)
    at oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:224)
    at oshi.software.common.AbstractOperatingSystem.getProcess(AbstractOperatingSystem.java:221)
    at kamon.instrumentation.system.process.ProcessMetricsCollector$MetricsCollectionTask.recordProcessULimits(ProcessMetricsCollector.scala:97)
    at kamon.instrumentation.system.process.ProcessMetricsCollector$MetricsCollectionTask.$anonfun$schedule$1(ProcessMetricsCollector.scala:63)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:671)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
```

**Comment by dbwiddis** [comment]
That sure looks like #1155, fixed in 4.6.1, before we even got to the 5.X versions.  

The line number 284 certainly doesn't match the current version, based on tags looks like it's version 4.2.1 or earlier.

**Comment by dbwiddis** [comment]
And for completeness, looks like the bug was introduced in #981, in version 4.1.0, but the line number matches 4.1.1, 4.2.0, or 4.2.1.  Based on [this diff](https://github.com/kamon-io/Kamon/commit/ad454c963bc63da2955381b57cb6ccb20de2bf74) looks like Kamon was using 4.2.1 until a few weeks ago, so this should be resolved by your switch to 5.2.5.

**Comment by dbwiddis** [comment]
You may wish to switch to 5.3.4 if you haven't released yet, as theres a bug listing services with newer versions of systemd.

**Comment by SimunKaracic** [comment]
Will bump to that version!

Thank you all for the assistance :+1: :tada:
