### ISSUE TITLE
NoSuchMethodError on Linux

### ISSUE THREAD

**Issue by RANKTW** [oshi/oshi#1477]
version
oshi-core-5.3.7
jna-5.6.0
jna-platform-5.6.0

on Linux

Exception in thread "main" java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
at com.sun.jna.platform.linux.Udev.(Udev.java:37)
at oshi.hardware.platform.linux.LinuxHWDiskStore.getDisks(LinuxHWDiskStore.java:160)
at oshi.hardware.platform.linux.LinuxHWDiskStore.getDisks(LinuxHWDiskStore.java:151)
at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getDiskStores(LinuxHardwareAbstractionLayer.java:75)

**Comment by dbwiddis** [comment]
You my have an older version of JNA in your class path from a transitive dependency.  See the README or FAQ for the NoClassDefFoundError issues.  The steps should be the same.

**Comment by RANKTW** [comment]
well this is NoSuchMethodError not NoClassDefFoundError 

and I only have this issue on Linux
works fine on windows

**Comment by dbwiddis** [comment]
Yep. :-)  The `NoClassDefFoundError` is the more common one with an older version of `jna-platform`.  But you can get the `NoSuchMethod` error if you have a 5.x `jna-platform` but a 4.x `jna` artifact.  I'll update the FAQ and README as well, as you're not the first (nor likely last) to see this.
