### ISSUE TITLE
Unable to cast to CFString. Type ID: 0

### ISSUE THREAD

**Issue by brettwooldridge** [oshi/oshi#1627]
I don't know if this is an issue with oshi or JNA, but...

OS: macOS Big Sur 11.4 Beta
JNA: 5.8.0
OSHI: 5.7.1
JVM: 11.0.11+9-LTS-194

```
Caused by: java.lang.ClassCastException: Unable to cast to CFString. Type ID: 0
	at com.sun.jna.platform.mac.CoreFoundation$CFStringRef.<init>(CoreFoundation.java:460)
	at oshi.software.os.mac.MacFileSystem.getFileStoreMatching(MacFileSystem.java:229)
	at oshi.software.os.mac.MacFileSystem.getFileStores(MacFileSystem.java:141)
	at oshi.software.common.AbstractFileSystem.getFileStores(AbstractFileSystem.java:55)
	at org.ziptie.zap.bootstrap.ZApplication.start(ZApplication.java:171)
```

The line of invocation looks like:
```java
171  systemInfo.getOperatingSystem().getFileSystem().getFileStores().stream()
172     .filter(fs -> "/data".equals(fs.getMount()))
173     .forEach(fs -> {
174        long totalSpace = fs.getTotalSpace();
175        long usableSpace = fs.getUsableSpace();
176        LOGGER.info("/data Disk Space (used/total): {}/{}", FormatUtil.formatBytes(totalSpace - usableSpace), FormatUtil.formatBytes(totalSpace));
177     });
```

Output of ``ls -l /Volumes``:
```
lrwxr-xr-x   1 root    wheel     1B Apr 24 03:09 Macintosh HD -> /
drwxrwxr-x@ 22 brettw  staff   816B Aug 11  2020 RAID1
drwxr-xr-x   1 brettw  staff   8.0K Apr 23 17:44 Untitled
drwxr-xr-x   3 root    wheel    96B May  2 04:39 com.apple.TimeMachine.localsnapshots
```

Output of ``mount``:
```
/dev/disk2s2s1 on / (apfs, sealed, local, read-only, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk2s5 on /System/Volumes/VM (apfs, local, noexec, journaled, noatime, nobrowse)
/dev/disk2s3 on /System/Volumes/Preboot (apfs, local, journaled, nobrowse)
/dev/disk2s6 on /System/Volumes/Update (apfs, local, journaled, nobrowse)
/dev/disk2s1 on /System/Volumes/Data (apfs, local, journaled, nobrowse)
/dev/disk3s3 on /Volumes/Untitled (ntfs, local, read-only, noowners)
map auto_home on /System/Volumes/Data/home (autofs, automounted, nobrowse)
/dev/disk5s2 on /Volumes/RAID1 (hfs, local, nodev, nosuid, journaled, noowners)
com.apple.TimeMachine.2021-05-02-033948.local@/dev/disk2s1 on /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/iMac (2)/2021-05-02-033948/Macintosh HD - Data (apfs, local, read-only, journaled, nobrowse)
```

**Comment by dbwiddis** [comment]
Probably a null that needs to be checked in getFileStores somewhere… will investigate.

**Comment by dbwiddis** [comment]
In an astonishingly easy to debug situation there's only one possibility for a problem here.

In `MacFileSystem` at line 228 we look up the volume name from the registry:
```
Pointer result = diskInfo.getValue(daVolumeNameKey);
CFStringRef volumePtr = new CFStringRef(result);
```
The exception being thrown is because `result` is `null` and is not checked before attempting to create the `CFString`. In JNA:
```
public CFStringRef(Pointer p) {
    super(p);
    if (!isTypeID(STRING_TYPE_ID)) {
        throw new ClassCastException("Unable to cast to CFString. Type ID: " + getTypeID());
    }
}
```
Where the typeID ends up 0 here:
```
if (this.getPointer() == null) {
    return new CFTypeID(0);
}
```
The fix is to null check `result` and give the volume name a sensible default.

Interestingly there is a null check later on `volumePtr.stringValue()` being null, but it's impossible for that to return null.  We're just not null checking early enough.

The only confusing thing is why you might end up with a disk (`/dev/disk#s#`) with no name.  If this is this a repeatable situation, it might be helpful to know something about what type of volume produces it. Otherwise it could be a race condition (e.g., time machine dismounting).
