### ISSUE TITLE
GraaIVM Native Image run fail

### ISSUE THREAD

**Issue by 18506711722** [oshi/oshi#1639]
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:903)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
Caused by: java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/win32-x86-64/jnidispatch.dll) not found in resource path ()
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1033)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:989)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at com.sun.jna.Structure.setAlignType(Structure.java:291)
	at com.sun.jna.Structure.<init>(Structure.java:208)
	at com.sun.jna.Structure.<init>(Structure.java:204)
	at com.sun.jna.Structure.<init>(Structure.java:191)
	at com.sun.jna.Structure.<init>(Structure.java:183)
	at com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX.<init>(WinNT.java:1967)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:59)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindows10OrGreater(VersionHelpers.java:194)
	at oshi.hardware.platform.windows.WindowsGlobalMemory.<clinit>(WindowsGlobalMemory.java:60)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createMemory(WindowsHardwareAbstractionLayer.java:56)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:80)
	at cn.tpddns.aion.controller.HomeController.initMemoryChart(HomeController.java:210)
	at cn.tpddns.aion.controller.HomeController.initOverviewTab(HomeController.java:145)
	at cn.tpddns.aion.controller.HomeController.initialize(HomeController.java:112)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2655)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3323)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3280)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3249)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3222)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3199)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3192)
	at cn.tpddns.aion.UIApplication.start(UIApplication.java:26)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:849)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:474)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
	at java.security.AccessController.doPrivileged(AccessController.java:100)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
	at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	... 3 more

**Comment by mprins** [comment]
the error is pretty clear, you have an unstatisfied link to the native library that is required:
> `Caused by: java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/win32-x86-64/jnidispatch.dll) not found in resource path ()`

so you need to fix that in your runtime
