### ISSUE TITLE
Windows 11 Beta

### ISSUE THREAD

**Issue by andreschardong** [oshi/oshi#1699]
I know windows 11 is probably not supported, however, I'm facing this issue when starting Geoserver. Was working fine before the update (windows 10). 

I have tried different versions of Java (x86 64bits, java 8-301 and others) same issue.

18 Aug 21:26:59 ERROR [context.ContextLoader] - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OSHISystemInfoCollector' defined in URL [jar:file:/C:/Geoserver/webapps/geoserver/WEB-INF/lib/gs-main-2.19.2.jar!/org/geoserver/system/status/OSHISystemInfoCollector.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geoserver.system.status.OSHISystemInfoCollector]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Unmapped relationship: 7
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1300)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)

**Comment by dbwiddis** [comment]
This looks like #1554, a problem in JNA.   It can be fixed by updating your JNA dependency to 5.8.0 or newer.   (5.9.0 should be released within the week.)

**Comment by dbwiddis** [comment]
Of note, it appears GeoServer [depends on OSHI 5.5.1](https://github.com/geoserver/geoserver/blob/bd66b26706ae982a52151114328db5e53966420f/src/pom.xml#L1332-L1336) which in turn depends on an earlier JNA version.  Depending on an OSHI version 5.6.1 or later (current is 5.9.0) will thus include the newer JNA transitive dependency. 

I'll leave @mprins to consider whether GeoServer should update.

**Comment by mprins** [comment]
I will prepare a PR to update GeoServer, it should be in time for the next major release

**Comment by andreschardong** [comment]
Great! Thanks for investigating so promptly.  I guess we can close the issue?

**Comment by dbwiddis** [comment]
FYI, I'm now on Windows 11 on my work machine and OSHI works fine.

Well, technically some beta version still labeled 10...
```
2021-08-31 15:19:07.770 [INFO] SystemInfoTest - Printing Operating System and Hardware Info:
Microsoft Windows 10 build 22000
```
