### ISSUE TITLE
Using this inside spring-native

### ISSUE THREAD

**Issue by bojanv55** [oshi/oshi#1740]
Is it possible to make this work inside spring-native compiled binary?

Currently when I try to compile I get this error:

```
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/win32-x86-64/jnidispatch.dll) not found in resource path ()
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1033) ~[na:na]
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:989) ~[na:na]
        at com.sun.jna.Native.<clinit>(Native.java:195) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295) ~[na:na]
        at com.sun.jna.Structure.setAlignType(Structure.java:291) ~[na:na]
        at com.sun.jna.Structure.<init>(Structure.java:208) ~[na:na]
        at com.sun.jna.Structure.<init>(Structure.java:204) ~[na:na]
        at com.sun.jna.Structure.<init>(Structure.java:191) ~[na:na]
        at com.sun.jna.Structure.<init>(Structure.java:183) ~[na:na]
        at com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX.<init>(WinNT.java:1973) ~[na:na]
        at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:59) ~[na:na]
        at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVistaOrGreater(VersionHelpers.java:127) ~[na:na]
        at oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:108) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295) ~[na:na]
        at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:118) ~[na:na]
        at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[na:na]
        at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:112) ~[na:na]
        at com.example.demo.RunIt.run(RunIt.java:20) ~[native-tests.cmd.exe:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) ~[native-tests.cmd.exe:2.5.5]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) ~[native-tests.cmd.exe:2.5.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[native-tests.cmd.exe:2.5.5]
        at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:123) ~[native-tests.cmd.exe:2.5.5]
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99) ~[native-tests.cmd.exe:5.3.10]
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124) ~[native-tests.cmd.exe:5.3.10]
        at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124) ~[na:na]
        at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118) ~[native-tests.cmd.exe:5.3.10]
        at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83) ~[native-tests.cmd.exe:5.3.10]
        at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:43) ~[native-tests.cmd.exe:na]
        at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:248) ~[na:na]
        at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:138) ~[native-tests.cmd.exe:5.3.10]
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$6(ClassBasedTestDescriptor.java:350) ~[na:na]
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:355) ~[na:na]
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$7(ClassBasedTestDescriptor.java:350) ~[na:na]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) ~[na:na]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[na:na]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[na:na]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[na:na]
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstancePostProcessors(ClassBasedTestDescriptor.java:349) ~[na:na]
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$instantiateAndPostProcessTestInstance$4(ClassBasedTestDescriptor.java:270) ~[na:na]
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[na:na]
...
```

**Comment by dbwiddis** [comment]
This is a problem with JNA, not OSHI.
1. The line numbers in your stack trace indicate you are using JNA version 5.7.0.  While that may not be the root cause of this error, you should generally try to use the latest version as a first troubleshooting step.
2. The error indicates an ability to load JNA's native library, which is normally extracted to a temporary directory.   You need to investigate which part of this process is failing.
 - Various issues such as having write permission to create this directory can prevent this.  A potential fix here is to move that dll out of the JNA jar and into a directory on your `PATH`.  
 - It's possible you need to load the JNA jar file somewhere other than where you have it.

Are you using the Spring Boot Starter Parent? Versions 2.2 and earlier include JNA as a dependency and can cause issues. Upgrade to version 2.3 or later, or adjust the jna-version property to the latest JNA version (currently 5.9.0).

**Comment by dbwiddis** [comment]
Well now it's OSHI not finding JNA on the class path.  

Some thoughts:
 - I see that the project you linked to indicates it's set up for GraalVM on Linux x86-64.  But the code above is trying to open a windows DLL (Kernel32).  Can you clarify what your operating system is?
 - It's loading kernel32 properly into your "Kernelz32" class (this is how you are getting the JNA version) but not loading kernel32 again when OSHI tries to load it.   I'm not sure, but I suspect loading the same DLL into two separate library classes may be causing a problem.    Can you just use Kernel32.INSTANCE (from JNA) without creating your own?

**Comment by bojanv55** [comment]
It actually works OK with my Kernelz32 implementation of the single method. it outputs

```
1817802968
Hello there!
JNA Version::5.9.0
...
```

**Comment by dbwiddis** [comment]
Right. My point is that by loading your own implementation you may be blocking it from re-loading elsewhere where it is needed.

**Comment by dbwiddis** [comment]
Try adding a `extends com.sun.jna.platform.win32.Kernel32` on your implementation.

**Comment by bojanv55** [comment]
I implemented my own afterwards - just to try if it works. Does not matter if I remove it...

**Comment by Krillsson** [comment]
@bojanv55 I'm also looking into running oshi inside a spring native image. Care to share your configuration to how you got it working?

**Comment by Krillsson** [comment]
Here is what worked for me. I read [Springs documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html).

Then I used [GraalVMs tracing agent](https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/#tracing-agent) to generate additional .json config files that I put in src/resources/META-INF/native-image/[group-id]/[artifact-id]

OSHI has platform specific code, so the tracing agent has to be run on any additional platform you'd like to support. The tracing agent support merging of config files. And then you need a build per architecture you'd like.

I had to manually add some classes to my reflect-config.json after the tracing agent had done it's job.
