### ISSUE TITLE
getOperatingSystem().getProcesses() throws exception about missing method on jna 5.9.0

### ISSUE THREAD

**Issue by Axinet** [oshi/oshi#1787]
https://github.com/oshi/oshi/blob/38744bb456ee9b47b745596b5de442db0b181a12/oshi-core/pom.xml#L26

getOperatingSystem().getProcesses() throws exception about missing method on jna 5.9.0, but works when using jna & jna-patform 5.10.0. Looks like the issue shows up after recent Windows 10 update.

```
Caused by: java.lang.AbstractMethodError: com.sun.jna.Structure.getFieldOrder()Ljava/util/List;
	at com.sun.jna.Structure.fieldOrder(Structure.java:936)
	at com.sun.jna.Structure.getFields(Structure.java:962)
	at com.sun.jna.Structure.deriveLayout(Structure.java:1129)
	at com.sun.jna.Structure.calculateSize(Structure.java:1053)
	at com.sun.jna.Structure.calculateSize(Structure.java:1006)
	at com.sun.jna.Structure.allocateMemory(Structure.java:393)
	at com.sun.jna.Structure.<init>(Structure.java:184)
	at com.sun.jna.Structure.<init>(Structure.java:172)
	at com.sun.jna.Structure.<init>(Structure.java:159)
	at com.sun.jna.Structure.<init>(Structure.java:151)
	at com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX.<init>(WinNT.java:1973)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:59)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVistaOrGreater(VersionHelpers.java:127)
	at oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:108)
	at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:118)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:112)
```

**Comment by mprins** [comment]
it's unclear what version of oshi you are using.

jna was updated on `master`at https://github.com/oshi/oshi/commit/d81adb647223e0fb593a86e7e044dfa29f56f42f 2 weeks ago but is as yet unreleased. 
You can probably upgrade/override jna in your project as a workaround (as you seem to have done already)

**Comment by Axinet** [comment]
Sorry, I am using newest stable version available on mvn: `5.8.3`  (https://mvnrepository.com/artifact/com.github.oshi/oshi-core/5.8.3).
Yes, I forced newer jna version and it works then. 
Placing the solution here may also help someone else find the way to overcome issue :).

**Comment by dbwiddis** [comment]
This is interesting as JNA didn't make any changes in 5.10.0 that would have been relevant here.   I'll dig into this a little later today.

**Comment by dbwiddis** [comment]
So it looks like the `AbstractMethodError` at runtime is associated with an old compiled version. While the version change forced recompiling, it’s likely a `mvn clean` would have worked even with 5.9.0.

**Comment by dbwiddis** [comment]
Closing this as it's a transient issue resolved by forcing recompilation. :)

**Comment by Axinet** [comment]
Sorry for taking your time :(. 
Without specifing jna version explicit, one of other dependencies lowered its version much lower whan 5.9.0 (4.x line) 🤦‍♂️.

**Comment by dbwiddis** [comment]
No worries at all. 

You can influence the higher version by putting it earlier in your dependency list.
