### ISSUE TITLE
Mac M1 Pro compatible error

### ISSUE THREAD

**Issue by nikerxu** [oshi/oshi#1985]
when run in Macbook M1 pro, it throws this error:
Caused by: java.lang.NoClassDefFoundError: com/sun/jna/platform/mac/SystemB$Timeval
 at oshi.software.os.mac.MacOperatingSystem.<clinit>(MacOperatingSystem.java:87) ~[oshi-core-6.1.5.jar:6.1.5]
 at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:108) ~[oshi-core-6.1.5.jar:6.1.5]
 at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.1.5.jar:6.1.5]
 at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:98) ~[oshi-core-6.1.5.jar:6.1.5]

**Comment by dbwiddis** [comment]
https://github.com/oshi/oshi/blob/master/src/site/markdown/FAQ.md#how-do-i-resolve-jna-noclassdeffounderror-or-nosuchmethoderror-issues
