### ISSUE TITLE
JNA issues on Windows 10 

### ISSUE THREAD

**Issue by aguedeney** [oshi/oshi#2003]
The stack exception is based on 6.1.5.  It's been working fine on 5.3.6.

I've confirmed that (on Windows 10 Professional) this problem starts at version 5.5.0 and onward. It works fine on Mac and Linux.

I'm using java version "1.8.0_321".

Apr 07, 2022 2:20:45 AM com.sun.jna.Native extractFromResourcePath
INFO: Looking in classpath from sun.misc.Launcher$AppClassLoader@5c647e05 for /com/sun/jna/win32-x86-64/jnidispatch.dll
Apr 07, 2022 2:20:45 AM com.sun.jna.Native extractFromResourcePath
INFO: Found library resource at jar:file:/C:/cygwin64/home/user1/vfy-install.jar!/com/sun/jna/win32-x86-64/jnidispatch.dll
Apr 07, 2022 2:20:45 AM com.sun.jna.Native extractFromResourcePath
INFO: Extracting library to C:\Users\user1\AppData\Local\Temp\jna--657823221\jna4751583357198103337.dll
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't obtain class com.sun.jna.CallbackReference
        at com.sun.jna.Native.initIDs(Native Method)
        at com.sun.jna.Native.<clinit>(Native.java:248)
        at com.sun.jna.Structure.setAlignType(Structure.java:291)
        at com.sun.jna.Structure.<init>(Structure.java:208)
        at com.sun.jna.Structure.<init>(Structure.java:204)
        at com.sun.jna.Structure.<init>(Structure.java:191)
        at com.sun.jna.Structure.<init>(Structure.java:183)
        at com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX.<init>(WinNT.java:1980)
        at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:59)
        at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVistaOrGreater(VersionHelpers.java:127)
        at oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:109)
        at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:104)
        at oshi.util.Memoizer$1.get(Memoizer.java:87)
        at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:98)

**Comment by dbwiddis** [comment]
There were no changes in OSHI related to that method, however OSHI did update to JNA 5.7.0 with that version, and I know the native libraries were rebuilt as part of that.  
1. What version of JNA are you using?  The latest is 5.11.0, and you need 5.10.0 for the current OSHI release.
2. If you're on the newest JNA, try cleaning out that temp directory in the log file: `C:\Users\user1\AppData\Local\Temp\` to make sure the old JNA stub isn't reloading.

If both of those fail, bring up the issue on the jna-users mailing list.

**Comment by aguedeney** [comment]
> There were no changes in OSHI related to that method, however OSHI did update to JNA 5.7.0 with that version, and I know some native libraries were rebuilt as part of that.
> 
> 1. What version of JNA are you using?  The latest is 5.11.0, and you need at least 5.10.0 (which also rebuilt libraries for libffi improvements) for the current OSHI release.
> 2. If you're on the newest JNA, try cleaning out that temp directory in the log file: `C:\Users\user1\AppData\Local\Temp\` to make sure the old JNA stub isn't reloading.
> 
> If both of those fail, bring up the issue on the [jna-users mailing list](https://groups.google.com/g/jna-users).

This is very good information and advice.  I'm using a shaded jar with minimize jar set to true (which is fine).  My culprit was a (user error) <exclude>META-INF/native/**</exclude>.  I knew it was something I was doing wrong. I hope this helps someone else in the future.
