### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Unmapped relationship: 7

### ISSUE THREAD

**Issue by VictorJSalasM** [oshi/oshi#2006]
I have this trouble
Im using Win 11 21H2 SO 22000.556
Exception in thread "main" java.lang.IllegalStateException: Unmapped relationship: 7
	at com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer(WinNT.java:3033)
	at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx(Kernel32Util.java:715)
	at oshi.driver.windows.LogicalProcessorInformation.getLogicalProcessorInformationEx(LogicalProcessorInformation.java:61)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:155)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:74)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:66)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:61)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68)
	at te6clienteservidor.cliente.main(cliente.java:38)
C:\Users\Victor\AppData\Local\NetBeans\Cache\13\executor-snippets\run.xml:111: The following error occurred while executing this line:
C:\Users\Victor\AppData\Local\NetBeans\Cache\13\executor-snippets\run.xml:68: Java returned: 1
BUILD FAILED (total time: 0 seconds)

**Comment by VictorJSalasM** [comment]
Im using the oshi latest version

**Comment by dbwiddis** [comment]
You are using an older version of JNA as a dependency.  This issue was resolved in JNA version 5.8.0 or newer.

See #1554 (or #1699 or #1780).
