### ISSUE TITLE
Exception oshi.driver 

### ISSUE THREAD

**Issue by LaDerek** [oshi/oshi#2011]
Windows 10 (18363.1556) build 1909

Exception in thread "HardwareInfo Collector Thread" java.lang.ExceptionInInitializerError
        at oshi.driver.windows.perfmon.PhysicalDisk.queryDiskCounters(Unknown Source)
        at oshi.hardware.platform.windows.WindowsHWDiskStore.queryReadWriteStats(Unknown Source)
        at oshi.hardware.platform.windows.WindowsHWDiskStore.getDisks(Unknown Source)
        at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getDiskStores(Unknown Source)
        at pro.gravit.launcher.RIVAPaCkSlauNcHER.RivApacksLAUNCHEr(Unknown Source)
        at pro.gravit.launcher.RIVAPaCkSlauNcHER.RivaPAcKSLAUNcheR(Unknown Source)
        at pro.gravit.launcher.rIVapaCkSLAUncHEr.RIvAPackSlAUNchEr(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unexpected registry type 1, expected REG_DWORD
        at com.sun.jna.platform.win32.Advapi32Util.registryGetIntValue(Unknown Source)
        at com.sun.jna.platform.win32.Advapi32Util.registryGetIntValue(Unknown Source)
        at com.sun.jna.platform.win32.Advapi32Util.registryGetIntValue(Unknown Source)
        at oshi.driver.windows.perfmon.PerfmonDisabled.isDisabled(Unknown Source)
        at oshi.driver.windows.perfmon.PerfmonDisabled.<clinit>(Unknown Source)
        ... 8 more

**Comment by mprins** [comment]
Your report is missing key information for debugging and/or analysis.

**Comment by dbwiddis** [comment]
OSHI is looking in your registry for the key `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Disk\Performance` and value `Disable Performance Counters`.

Your value in this key is type 1, `REG_SZ`, a null-terminated string.  

Per Microsoft Documentations, [this is a `REG_DWORD` value](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc784382(v=ws.10))

You may also want to check `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance` and `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfProc\Performance` keys.

**Comment by LaDerek** [comment]
![image](https://user-images.githubusercontent.com/82894246/163690522-e29b010d-78c3-4071-8c1e-01c7e98128a4.png)

**Comment by LaDerek** [comment]
what I should do?

**Comment by LaDerek** [comment]
This helped, thx all
![image](https://user-images.githubusercontent.com/82894246/163690776-8693e88c-40e3-46ea-9a50-2fa51d5075b7.png)
