### ISSUE TITLE
OSHI process info fails on Windows server core docker image

### ISSUE THREAD

**Issue by georgblumenschein** [oshi/oshi#2026]
Hello,

I am having trouble to run test with oshi on different Windows Versions. I am getting the dependency via Gradle.
```
api 'com.github.oshi:oshi-core:4.6.1'
```

On Windows 11 (Microsoft Windows [Version 10.0.22000.613]) every version smaller than 5.2.5 fails in the os.getProcess call.

```
java.lang.NullPointerException
	at oshi.driver.windows.registry.ProcessPerformanceData.buildProcessMapFromRegistry(ProcessPerformanceData.java:81)
	at oshi.software.os.windows.WindowsOperatingSystem.queryProcessMapFromRegistry(WindowsOperatingSystem.java:522)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.software.os.windows.WindowsOperatingSystem.processMapToList(WindowsOperatingSystem.java:337)
	at oshi.software.os.windows.WindowsOperatingSystem.getProcess(WindowsOperatingSystem.java:321)
	at oshi.software.common.AbstractOperatingSystem.getProcess(AbstractOperatingSystem.java:221)
```
Versions greater or equal 5.2.5 (Did not test all, but at least 5.2.5, 6.1.5, 6.1.6) fail on a docker image that is running on Windows Server 2019 1806 and using mcr.microsoft.com/windows/servercore:ltsc2019 as a base image
```
[HkeyPerformanceDataUtil] - Unable to locate English counter names in registry Perflib 009. Counters may need to be rebuilt: 
com.sun.jna.platform.win32.Win32Exception: The system cannot find the file specified.
	at com.sun.jna.platform.win32.Advapi32Util.registryGetStringArray(Advapi32Util.java:951)
	at com.sun.jna.platform.win32.Advapi32Util.registryGetStringArray(Advapi32Util.java:926)
	at com.sun.jna.platform.win32.Advapi32Util.registryGetStringArray(Advapi32Util.java:900)
	at oshi.driver.windows.registry.HkeyPerformanceDataUtil.mapCounterIndicesFromRegistry(HkeyPerformanceDataUtil.java:301)
	at oshi.driver.windows.registry.HkeyPerformanceDataUtil.<clinit>(HkeyPerformanceDataUtil.java:69)
	at oshi.driver.windows.registry.ProcessPerformanceData.buildProcessMapFromRegistry(ProcessPerformanceData.java:69)
	at oshi.software.os.windows.WindowsOperatingSystem.queryProcessMapFromRegistry(WindowsOperatingSystem.java:327)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.software.os.windows.WindowsOperatingSystem.processMapToList(WindowsOperatingSystem.java:307)
	at oshi.software.os.windows.WindowsOperatingSystem.getProcess(WindowsOperatingSystem.java:301)
```

Windows 10 (Build 19044) seems unaffected, same for Linux.

Can you please help me there? :)
Thanks in advance.

**Comment by dbwiddis** [comment]
The bug prior to 5.2.5 was probably fixed in #1320 (fixing #1319) which went in as part of 5.2.5.

The issue with performance counters inside a container looks similar to the report in #1976.  This issue is external to OSHI; apparently containers do not (by default) have access to the host system's performance counters, and they must be enabled in a configuration.  

I am not familiar with special settings required to enable performance counters inside a Docker container, but I believe it is something that can be configured in the container.  

Attempt to use other code that accesses the performance counters from inside the container (e.g., use `TypePerf` or execute `PerfMon`, etc.).  I would suggest searching and/or inquiring on support forums for Windows-based Docker containers.

**Comment by dbwiddis** [comment]
I'm sure there's _a_ solution somewhere, but I do think a Docker support forum is more likely to be able to give specific help.

**Comment by dbwiddis** [comment]
Still looking into this.  I notice you are using the "core image":

> using mcr.microsoft.com/windows/servercore:ltsc2019 as a base image

According to [the docs](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-base-images):

> **Choosing a base image**
> How do you choose the right base image to build upon? For most users, Windows Server Core and Nanoserver will be the most appropriate image to use. Each base image is briefly described below:
> 
> - Nano Server is an ultralight Windows offering for new application development.
> - Server Core is medium in size and a good option for "lifting and shifting" Windows Server apps.
> - Windows is the largest image and has full Windows API support for workloads.
> - Windows Server is slightly smaller than the Windows image, has full Windows API support, and allows you to use more server features.

It appears the nano and core options do not have "full Windows API support".  I would suggest using the "Windows Server" image to see if this resolves the issue.

**Comment by dbwiddis** [comment]
> docker image that is running on Windows Server 2019 1806

I notice [this bug](https://docs.microsoft.com/en-us/troubleshoot/windows-server/virtualization/api-call-performance-counters-delay-container) impacting performance counters on Windows Server Containers.  They list various versions including 1803 and 1809 (but not 1806?) but you might try the workaround in that article, or try a newer version.

**Comment by georgblumenschein** [comment]
Thanks, I will check if an upgrade is possible

**Comment by dbwiddis** [comment]
Hey @georgblumenschein, have you had any success with this?

**Comment by dbwiddis** [comment]
Closing this issue as this may be an external bug with a workaround posted.  Feel free to reopen if you are still experiencing problems.
