### ISSUE TITLE
`NoClassDefFoundError` when use `oshi` in docker

### ISSUE THREAD

**Issue by chingjustwe** [oshi/oshi#2092]
## background

Hi, I use `oshi` to get system info, and it works perfectly on *windows*, *linux* and *mac*.
Now I need to containerize my application, but I got a `java.lang.NoClassDefFoundError: com/sun/jna/platform/linux/Udev`.

## sample code
~~~java
    SystemInfo systemInfo = new SystemInfo();
    HardwareAbstractionLayer hardwareAbstractionLayer = systemInfo.getHardware();
    // got exception on below line
    int cpuCount = hardwareAbstractionLayer.getProcessor().getPhysicalProcessorCount()
~~~

## full stack trace
~~~
Caused by: java.lang.NoClassDefFoundError: com/sun/jna/platform/linux/Udev
        at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:166)
        at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83)
        at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:64)
        at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62)
        at oshi.util.Memoizer$1.get(Memoizer.java:87)
        at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68)
        at com.test.service.impl.NodeStatusServiceImpl.getNodeStatus(NodeStatusServiceImpl.java:100)
        at com.test.service.impl.NodeStatusServiceImpl.updateNodeStatus(NodeStatusServiceImpl.java:69)
        at com.test.scheduler.WriteNodeStatusTask.execute(WriteNodeStatusTask.java:22)
        at com.test.scheduler.BaseTask.launch(BaseTask.java:60)
        at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:280)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
        ... 3 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.linux.Udev
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 18 common frames omitted
~~~

## `oshi` version
~~~xml
    <dependency>
        <groupId>com.github.oshi</groupId>
        <artifactId>oshi-core</artifactId>
        <version>6.1.6</version>
    </dependency>
~~~

## my docker file
~~~docker
FROM openjdk:8-jdk-alpine
WORKDIR /opt/test
ADD target/app.jar ./
ENV JAR_FILE /opt/test/app.jar
EXPOSE 18088
ENTRYPOINT ["/bin/sh", "-c", "java -Dsun.misc.URLClassPath.disableJarChecking=true -jar $JAR_FILE"]
~~~

- - -
BTW, issue happens on both `Mac` and `CentOS7`, looking forward to your reply.

**Comment by chingjustwe** [comment]
Thanks @dbwiddis for your quick reply, I will give it a shot.

**Comment by chingjustwe** [comment]
I still got a `java.lang.NoClassDefFoundError: oshi.software.os.linux.LinuxOperatingSystem` after upgrade to version **6.2.0**.
Finally I got it resolved by changing my spring boot version from **2.1.3.RELEASE** to **2.7.1**.

**Comment by dbwiddis** [comment]
Great, glad you've got it sorted.
