### ISSUE TITLE
Pdh call failed with error code 0xC0000BB8

### ISSUE THREAD

**Issue by microwin7** [oshi/oshi#2111]
```log
2022.07.09 14:06:57 [INFO] Your Hardware ID:
2022.07.09 14:06:57 [INFO] Create HWIDProvider instance: 124 ms
2022.07.09 14:06:57 [INFO] Bitness: 64, totalMemory: 12788666368(11.910 GB), battery true, TIME: 131 ms
2022.07.09 14:06:58 [INFO] Processors || logical: 4 physical 2 freq 2400000000, TIME: 205 ms
2022.07.09 14:06:59 [ERROR] com.sun.jna.platform.win32.PdhUtil$PdhException: Pdh call failed with error code 0xC0000BB8
	at com.sun.jna.platform.win32.PdhUtil.PdhEnumObjectItems(Unknown Source)
	at oshi.util.platform.windows.PerfCounterWildcardQuery.queryInstancesAndValuesFromPDH(Unknown Source)
	at oshi.util.platform.windows.PerfCounterWildcardQuery.queryInstancesAndValues(Unknown Source)
	at oshi.driver.windows.perfmon.PhysicalDisk.queryDiskCounters(Unknown Source)
	at oshi.hardware.platform.windows.WindowsHWDiskStore.queryReadWriteStats(Unknown Source)
	at oshi.hardware.platform.windows.WindowsHWDiskStore.getDisks(Unknown Source)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getDiskStores(Unknown Source)
	at pro.gravit.launcher.wmLAunchyEylhG.WmLauNCh3PZfbw(Unknown Source)
	at pro.gravit.launcher.WmLaUnCHP4got7.invoke(Unknown Source)
	at pro.gravit.utils.command.CommandHandler.eval(Unknown Source)
	at pro.gravit.utils.command.CommandHandler.evalNative(Unknown Source)
	at pro.gravit.launcher.wmLAUNcHpDR5BR.WMlauNcH2nuJmK(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8792)
	at javafx.controls/com.sun.javafx.scene.control.behavior.TextFieldBehavior.fire(TextFieldBehavior.java:154)
	at javafx.controls/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(TextInputControlBehavior.java:332)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4105)
	at javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2156)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2630)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:218)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:150)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:250)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:249)
	at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:548)
	at javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:972)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
Version oshi 6.2.1
JNA 5.12.1
JNA-platform 5.12.1

**Comment by dbwiddis** [comment]
I don't think you're on OSHI 6.2.1.

Your stack trace has "Unknown Source" rather than line numbers so I can't guess what version you're on, but this stack trace is impossible in OSHI 6.2.1:
```
2022.07.09 14:06:59 [ERROR] com.sun.jna.platform.win32.PdhUtil$PdhException: Pdh call failed with error code 0xC0000BB8
	at com.sun.jna.platform.win32.PdhUtil.PdhEnumObjectItems(Unknown Source)
	at oshi.util.platform.windows.PerfCounterWildcardQuery.queryInstancesAndValuesFromPDH(Unknown Source)
```
The call to PdhUtil.PdhEnumObjectItems catches that `PdhException`:
https://github.com/oshi/oshi/blob/de77ae0ec230ed43af208514e92c7c66986417c2/oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterWildcardQuery.java#L132-L138

Please investigate your transitive dependencies.

**Comment by microwin7** [comment]
Thanks
I checked and it's true, apparently the user of the software did not assemble the program after updating the libraries. Now everything works.

**Comment by dbwiddis** [comment]
Good to hear. Having finally fixed a bug that had been there for 4 years I was hoping it wasn't a zombie! 😁 🧟
