### ISSUE TITLE
looking for the reason for NPE in LinuxNetworkParams.getDomainName call.

### ISSUE THREAD

**Issue by kushalagrawal** [oshi/oshi#2237]
Hi,

We are seeing the NPE in the `LinuxNetworkParams.getDomainName` call in oshi version `6.1.6`. Although I am not able to see any reason for this.  Can anyone help me when with the reasons why this can throw NPE?
```
Caused by: java.lang.NullPointerException
	at oshi.software.os.linux.LinuxNetworkParams.getDomainName(LinuxNetworkParams.java:80) ~[oshi-core-6.1.6.jar!/:6.1.6]
	at com.airwatch.common.diagnostics.DiagnosticCollector.fetchSystemConfiguration(DiagnosticCollector.java:148) ~[diagnostic-library-2.0.3.jar!/:?]
```

Here is the method where I am getting the error : 
```
@Override
    public String getDomainName() {
        try (Addrinfo hint = new Addrinfo()) {
            hint.ai_flags = CLibrary.AI_CANONNAME;
            String hostname = "";
            try {
                hostname = InetAddress.getLocalHost().getHostName();
            } catch (UnknownHostException e) {
                LOG.warn("Unknown host exception when getting address of local host: {}", e.getMessage());
                return "";
            }
            try (CloseablePointerByReference ptr = new CloseablePointerByReference()) {
                int res = LIBC.getaddrinfo(hostname, null, hint, ptr);
                if (res > 0) {
                    if (LOG.isErrorEnabled()) {
                        LOG.error("Failed getaddrinfo(): {}", LIBC.gai_strerror(res));
                    }
                    return "";
                }
                try (Addrinfo info = new Addrinfo(ptr.getValue())) {
                    return info.ai_canonname == null ? hostname : info.ai_canonname.trim();
                }
            }
        }
    }
```

**Comment by mprins** [comment]
https://github.com/oshi/oshi/blob/62f8ad86dc7875c9d3b775882b311a0776abbb69/oshi-core/src/main/java/oshi/software/os/linux/LinuxNetworkParams.java#L80

perhaps the canonical name is empty
