### ISSUE TITLE
weird message in the logs

### ISSUE THREAD

**Issue by andriy-gerasika** [oshi/oshi#2255]
Hi,
we are receving a weird message in our logs:
```
2022-11-17T12:46:08.609Z [TRACE:oshi.util.ParseUtil] -  didn't parse. Returning default. {}: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at oshi.util.ParseUtil.parseIntOrDefault(Unknown Source)
	at oshi.util.ParseUtil.getNthIntValue(Unknown Source)
	at oshi.util.ParseUtil.getFirstIntValue(Unknown Source)
	at oshi.hardware.platform.mac.MacCentralProcessor.queryArmCpu(Unknown Source)
	at oshi.hardware.platform.mac.MacCentralProcessor.initProcessorCounts(Unknown Source)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(Unknown Source)
	at oshi.hardware.platform.mac.MacCentralProcessor.<init>(Unknown Source)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.createProcessor(Unknown Source)
	at oshi.util.Memoizer$1.get(Unknown Source)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(Unknown Source)
	at com.medtronic.diabetes.solar.Solar.login(Native Method)
	at com.medtronic.diabetes.solar.uploader.action.LoginAction.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
it probably means nothing but this message somewhat messes up our logs and creates confusion like there is some bug -- is it possible to get rid of this message?
p.s.
oshi-core version is 6.3.2

Thank You

**Comment by dbwiddis** [comment]
Hey @andriy-gerasika thanks for this report.  I'm not finding the `queryArmCpu()` method shown in the stack trace in the 6.3.2 version.  It looks like it was removed in #2118 in 6.2.2.

That said, looking at the old code I can see the logic that generated the log: iterating the registry looking for "cpu0", "cpu1", etc. but there was a known "cpu" entry that was intentionally ignored and handled after parsing.  I can certainly move that to a regex match to avoid this (one-time) trace log entry.

**Comment by dbwiddis** [comment]
https://github.com/oshi/oshi/blob/05f75479f73cbd65df5143bda14344e492d93db6/oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java#L294-L295
