### ISSUE TITLE
Java 18 unsupported? `java.lang.NoSuchMethodError: 'void com.sun.jna.Memory.close()`

### ISSUE THREAD

**Issue by Osiris-Team** [oshi/oshi#2282]
Getting this when trying to get CPU info, when using Java 18 on Windows:
```sh
Exception in thread "Thread-8" java.lang.NoSuchMethodError: 'void com.sun.jna.Memory.close()'
        at oshi.util.Util.freeMemory(Util.java:83)
        at oshi.jna.ByRef$CloseableLONGLONGByReference.close(ByRef.java:81)
        at oshi.util.platform.windows.PerfDataUtil.updateQueryTimestamp(PerfDataUtil.java:151)
        at oshi.util.platform.windows.PerfCounterQueryHandler.updateQuery(PerfCounterQueryHandler.java:113)
        at oshi.util.platform.windows.PerfCounterWildcardQuery.queryInstancesAndValuesFromPDH(PerfCounterWildcardQuery.java:133)
        at oshi.util.platform.windows.PerfCounterWildcardQuery.queryInstancesAndValues(PerfCounterWildcardQuery.java:62)        at oshi.driver.windows.perfmon.ProcessorInformation.queryFrequencyCounters(ProcessorInformation.java:189)
        at oshi.hardware.platform.windows.WindowsCentralProcessor.queryCurrentFreq(WindowsCentralProcessor.java:213)
        at oshi.util.Memoizer$1.get(Memoizer.java:61)
        at oshi.hardware.common.AbstractCentralProcessor.getCurrentFreq(AbstractCentralProcessor.java:124)
        at com.osiris.autoplug.client.network.online.connections.ConSendPrivateDetails.lambda$open$0(ConSendPrivateDetails.java:66)
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: java.lang.NoSuchMethodError: 'void com.sun.jna.Memory.close()'
                at oshi.util.Util.freeMemory(Util.java:83)
                at oshi.jna.ByRef$CloseableHANDLEByReference.close(ByRef.java:95)
                at oshi.util.platform.windows.PerfCounterQueryHandler.removeAllCounters(PerfCounterQueryHandler.java:91)
                at oshi.util.platform.windows.PerfCounterQueryHandler.close(PerfCounterQueryHandler.java:144)
                at oshi.util.platform.windows.PerfCounterWildcardQuery.queryInstancesAndValuesFromPDH(PerfCounterWildcardQuery.java:115)
                ... 7 more
```

**Comment by dbwiddis** [comment]
You have a version of JNA prior to 5.12.  

Check your transitive dependencies. Make sure both JNA and JNA-platform are 5.12.1.

**Comment by Osiris-Team** [comment]
That should be it thanks!

**Comment by ZacSweers** [comment]
I am seeing this on Java 19 with JNA and JNA-platform `5.13.0`

**Comment by dbwiddis** [comment]
> I am seeing this on Java 19 with JNA and JNA-platform `5.13.0`

I suspect you have a lower JNA version from a transitive dependency.

**Comment by ZacSweers** [comment]
Nope!

<img width="862" alt="image" src="https://user-images.githubusercontent.com/1361086/219098419-3d61781b-6e52-4f83-a44f-7600dafaa1f2.png">

**Comment by dbwiddis** [comment]
Well JNA 5.13.0 has that method so there is an old jar there from somewhere... maybe clear cache/restart daemon, etc.  

Nothing I can do on this end.

**Comment by ZacSweers** [comment]
Figured it out, another gradle plugin was surprisingly repackaging JNA and winning on the classpath, causing a strange error like the above despite dependency resolution's reporting. Sorry for the false alarm!

**Comment by dbwiddis** [comment]
> Figured it out, another gradle plugin was surprisingly repackaging JNA and winning on the classpath, causing a strange error like the above despite dependency resolution's reporting. Sorry for the false alarm!

Great!  Was it associated with a gradle 8 upgrade?

How did you resolve that?  I've got a similar issue elsewhere with a gradle plugin introducing an older junit engine and I don't seem to be able to change plugin dependencies.  No issues on Gradle 7, jar hell in Gradle 8...

**Comment by ZacSweers** [comment]
Our case was fairly subtle. It coincided with putting sqldelight's gradle plugin on our root buildscript classpath, and it turns out it's accidentally repacking jna (but not relocating the package) in its jar and that was winning on the classpath

**Comment by dbwiddis** [comment]
Is there a fix in `build.gradle` or is it getting the plugin to fix their packaging?

**Comment by ZacSweers** [comment]
The proper fix is the latter, but I'm working around it in our build by putting jna dependencies on the settings.gradle buildscript classpath so it wins out over the root build.gradle one

**Comment by dbwiddis** [comment]
> I'm working around it in our build by putting jna dependencies on the settings.gradle buildscript classpath 

Thanks, I'll see if I can figure that part out!
