### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native

### ISSUE THREAD

**Issue by micartey** [oshi/oshi#2358]
Hello there!

I run into some strange error when using proguard while excluding `oshi` and `com.sun.jna`. Running it without proguard works, but isn't an option for me. Does anybody know how I can fix this?

```
[daniel@msi-desktop libs]$ java -jar -Djna.nosys=true -Djna.debug_load=true -Djna.debug_load.jna=true test-proguard.jar 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Apr 27, 2023 9:15:25 PM com.sun.jna.Native extractFromResourcePath
INFORMATION: Looking in classpath from sun.misc.Launcher$AppClassLoader@70dea4e for /com/sun/jna/linux-x86-64/libjnidispatch.so
Apr 27, 2023 9:15:25 PM com.sun.jna.Native extractFromResourcePath
INFORMATION: Found library resource at jar:file:/home/test-proguard.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
Apr 27, 2023 9:15:25 PM com.sun.jna.Native extractFromResourcePath
INFORMATION: Extracting library to /home/.cache/JNA/temp/jna8312583144518600645.tmp
Apr 27, 2023 9:15:25 PM com.sun.jna.Native c
INFORMATION: Trying /home/daniel/.cache/JNA/temp/jna8312583144518600645.tmp
Apr 27, 2023 9:15:25 PM com.sun.jna.Native c
INFORMATION: Found jnidispatch at /home/.cache/JNA/temp/jna8312583144518600645.tmp
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLong.<clinit>(Unknown Source)
	at oshi.util.FileUtil.readNativeLongFromBuffer(Unknown Source)
	at oshi.driver.linux.proc.Auxv.queryAuxv(Unknown Source)
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(Unknown Source)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(Unknown Source)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(Unknown Source)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(Unknown Source)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(Unknown Source)
	at oshi.util.Memoizer$1.get(Unknown Source)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(Unknown Source)
```

**Comment by micartey** [comment]
Nvm, I found the issue

**Comment by TheHaf** [comment]
Could you elaborate what the issue actually was? You'd be helping other people with the same error that came here via a search engine.

**Comment by micartey** [comment]
I used a gradle plugin to shadow the oshi dependency to another path. I enabled minimization but this removed classes that where actually used

**Comment by dbwiddis** [comment]
Sounds like another variation on the theme to add to the FAQ. :)

**Comment by TheHaf** [comment]
> I used a gradle plugin to shadow the oshi dependency to another path. I enabled minimization but this removed classes that where actually used

Thanks for sharing that info about a specific possible configuration issue with the community!
