### ISSUE TITLE
JNA import error

### ISSUE THREAD

**Issue by janezbozic** [oshi/oshi#2409]
Hello,

I have an issue with using Oshi on Android devices. When using:
```java
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hal = si.getHardware();
CentralProcessor cpu = hal.getProcessor();
```
The code returns an error.

Error stacktrace:
```
java.lang.NoClassDefFoundError: com.sun.jna.Native
    at oshi.jna.platform.linux.LinuxLibc.<clinit>(LinuxLibc.java:22)
    at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:97)
    at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:166)
    at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:65)
    at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:57)
    at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43)
    at oshi.hardware.common.AbstractHardwareAbstractionLayer$$ExternalSyntheticLambda1.get(Unknown Source:2)
    at oshi.util.Memoizer$1.get(Memoizer.java:61)
    at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
    at si.janez.testflapp.MainActivity.onCreate(MainActivity.java:34)
    at android.app.Activity.performCreate(Activity.java:8051)
    at android.app.Activity.performCreate(Activity.java:8031)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7839)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/android-aarch64/libjnidispatch.so) not found in resource path (.)
    at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1059)
    at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015)
    at com.sun.jna.Native.<clinit>(Native.java:221)
    at com.sun.jna.Native.load(Native.java:596)
    at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37)
    at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:79)
    at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:166) 
    at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:65) 
    at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:57) 
    at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) 
    at oshi.hardware.common.AbstractHardwareAbstractionLayer$$ExternalSyntheticLambda1.get(Unknown Source:2) 
    at oshi.util.Memoizer$1.get(Memoizer.java:61) 
    at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) 
    at si.janez.testflapp.MainActivity.onCreate(MainActivity.java:34) 
    at android.app.Activity.performCreate(Activity.java:8051) 
    at android.app.Activity.performCreate(Activity.java:8031) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loopOnce(Looper.java:201) 
    at android.os.Looper.loop(Looper.java:288) 
    at android.app.ActivityThread.main(ActivityThread.java:7839) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by dbwiddis** [comment]
See the FAQ: https://github.com/oshi/oshi/blob/master/src/site/markdown/FAQ.md#how-do-i-resolve-jna-noclassdeffounderror-or-nosuchmethoderror-issues

**Comment by janezbozic** [comment]
It's still not working. This is my build.gradle:
```
plugins {
    id 'com.android.application'
}

android {
    namespace 'si.janez.testflapp'
    compileSdk 33

    defaultConfig {
        applicationId "si.janez.testflapp"
        minSdk 30
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
    buildFeatures {
        viewBinding true
    }
    packagingOptions {
        resources.excludes.add("META-INF/AL2.0")
        resources.excludes.add("META-INF/LGPL2.1")
    }
}

dependencies {

    // implementation ('net.java.dev.jna:jna:5.13.0@aar')
    implementation group: 'com.github.oshi', name: 'oshi-core', version: '6.4.3'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
```

I have tried putting Oshi at the end, at the start, putting JNA separately at the end and at the start, and nothing works. If I out JNA separate dependency in the build.gradle, the error is duplicated classes. Am I doing something wrong?

**Comment by dbwiddis** [comment]
It would be very helpful if you could post the output of `gradle dependencies`.

Gradle should handle the duplicate dependencies, but specifying an AAR as you do may be duplicating the transitive JAR you get via OSHI. 

Note it's not only the `jna` dependency but also `jna-platform` that you need.  The class you aren't getting the correct version for is in `jna-platform`.

Gradle's dependency management is a little different than Maven, in that I don't think ordering matters. But from my experience there are a few things you could try:
1. Specify your own AAR dependency (both `jna` and `jna-platform`) as you do above and exclude it (the JAR) from OSHI, such as:
```groovy
  implementation ('net.java.dev.jna:jna:5.13.0@aar')
  implementation ('net.java.dev.jna:jna-platform:5.13.0@aar')
  implementation group: 'com.github.oshi', name: 'oshi-core', version: '6.4.3' {
    exclude group: 'net.java.dev.jna`
  }
```
2. Specify the JNA class versions as a constraint
```groovy
  constraints {
    implementation ('net.java.dev.jna:jna:5.13.0@aar')
    implementation ('net.java.dev.jna:jna-platform:5.13.0@aar')
  }
```
3. Use `resolutionStrategy.force()` to force the version:
```groovy
  resolutionStrategy.force('net.java.dev.jna:jna:5.13.0@aar')
  resolutionStrategy.force('net.java.dev.jna:jna-platform:5.13.0@aar')
```

**Comment by dbwiddis** [comment]
So earlier I didn't look more closely at your stack trace as it scrolled off the screen, but looking again, the error is not in getting the jar file, it's properly getting that JNA `Native` class path.   Where the problem appears is that it's not able to find the native library at the expected path `com/sun/jna/android-aarch64/libjnidispatch.so`.

So this does seem to be specific to android and the need for the AAR for the binaries, and option 1 above looks the most promising in that case.
