### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native

### ISSUE THREAD

**Issue by kbmts** [oshi/oshi#2430]
At first it was due to lack of disk space.

> `Application run failed java.nio.file.FileSystemException: /tmp/tomcat.34815.2266958638170805549: No space left on device`

So I added `-Djava.io.tmpdir=/e/tmp` to the springboot startup command.

But then another error appeared
```java
2023-08-13 16:21:28.272 [main] ERROR o.s.boot.SpringApplication Application run failed java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35)
	at oshi.util.FileUtil.readNativeLongFromBuffer(FileUtil.java:208)
	at oshi.driver.linux.proc.Auxv.queryAuxv(Auxv.java:39)
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:87)
	at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:85)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:76)
```

The system is `Ubuntu 20.04 LTS`,  and the dependency used is
```xml
<dependency>
    <groupId>com.github.oshi</groupId>
    <artifactId>oshi-core</artifactId>
    <version>6.4.0</version>
</dependency>
```

**Comment by dbwiddis** [comment]
Did you see the FAQ entries regarding Spring Boot?

JNA needs to write its native dll stub and it may be encountering the same disk space issue.  See the javadoc for JNA [Native](https://javadoc.io/static/net.java.dev.jna/jna/5.13.0/com/sun/jna/Native.html) class, particularly the section on Library Loading.

**Comment by kbmts** [comment]
I got it. Thank you very much.
