### ISSUE TITLE
NullPointerException in shi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture

### ISSUE THREAD

**Issue by alexstaeding** [oshi/oshi#2513]
I am getting the following error in a docker container on macOS.
Docker version 24.0.7, build afdd53b4e3 (latest at time of writing).

I can provide further details if necessary.

```
[init] Starting the Minecraft server...
2023-11-24T09:07:22.495610424Z Starting org.bukkit.craftbukkit.Main
2023-11-24T09:07:22.741142215Z System Info: Java 21 (OpenJDK 64-Bit Server VM 21.0.1+12-LTS) Host: Linux 6.4.16-linuxkit (aarch64)
2023-11-24T09:07:22.741163299Z Loading libraries, please wait...
2023-11-24T09:07:22.848241715Z 2023-11-24 09:07:22,847 ServerMain WARN Advanced terminal features are not available in this environment
2023-11-24T09:07:23.317494549Z [09:07:23 WARN]: Failed to get system info for Microarchitecture
2023-11-24T09:07:23.317520132Z java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
2023-11-24T09:07:23.317522341Z 	at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:6.4.5]
2023-11-24T09:07:23.317524299Z 	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
2023-11-24T09:07:23.317528382Z 	at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:6.4.5]
2023-11-24T09:07:23.317530382Z 	at net.minecraft.SystemReport.setDetail(SystemReport.java:62) ~[paper-1.20.2.jar:git-Paper-299]
2023-11-24T09:07:23.317531841Z 	at net.minecraft.SystemReport.putProcessor(SystemReport.java:153) ~[paper-1.20.2.jar:git-Paper-299]
2023-11-24T09:07:23.317533299Z 	at net.minecraft.SystemReport.lambda$putHardware$4(SystemReport.java:72) ~[paper-1.20.2.jar:git-Paper-299]
2023-11-24T09:07:23.317534632Z 	at net.minecraft.SystemReport.ignoreErrors(SystemReport.java:85) ~[paper-1.20.2.jar:git-Paper-299]
2023-11-24T09:07:23.317536049Z 	at net.minecraft.SystemReport.lambda$putHardware$4(SystemReport.java:72) ~[paper-1.20.2.jar:git-Paper-299]
2023-11-24T09:07:23.317537382Z 	at net.minecraft.SystemReport.lambda$new$2(SystemReport.java:47) ~[paper-1.20.2.jar:git-Paper-299]
2023-11-24T09:07:23.317538674Z 	at net.minecraft.SystemReport.ignoreErrors(SystemReport.java:85) ~[paper-1.20.2.jar:git-Paper-299]
2023-11-24T09:07:23.317540049Z 	at net.minecraft.SystemReport.lambda$new$2(SystemReport.java:47) ~[paper-1.20.2.jar:git-Paper-299]
2023-11-24T09:07:23.317549841Z 	at net.minecraft.CrashReport.<init>(CrashReport.java:32) ~[paper-1.20.2.jar:git-Paper-299]
2023-11-24T09:07:23.317551549Z 	at net.minecraft.CrashReport.preload(CrashReport.java:252) ~[paper-1.20.2.jar:git-Paper-299]
2023-11-24T09:07:23.317553299Z 	at net.minecraft.server.Main.main(Main.java:129) ~[paper-1.20.2.jar:git-Paper-299]
2023-11-24T09:07:23.317554674Z 	at org.bukkit.craftbukkit.Main.main(Main.java:324) ~[paper-1.20.2.jar:git-Paper-299]
2023-11-24T09:07:23.317555966Z 	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
2023-11-24T09:07:23.317557299Z 	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by dbwiddis** [comment]
See also https://github.com/PaperMC/Paper/issues/9785

I'm not sure where this comes from. 

The `cpuVendor` field is `final` so is thus set in the constructor, called from `MacCentralProcessor`.

For Apple Silicon the vendor comes from this code:
```java
private static String platformExpert() {
    String manufacturer = null;
    IORegistryEntry platformExpert = IOKitUtil.getMatchingService("IOPlatformExpertDevice");
    if (platformExpert != null) {
        // Get manufacturer from IOPlatformExpertDevice
        byte[] data = platformExpert.getByteArrayProperty("manufacturer");
        if (data != null) {
            manufacturer = Native.toString(data, StandardCharsets.UTF_8);
        }
        platformExpert.release();
    }
    return Util.isBlank(manufacturer) ? "Apple Inc." : manufacturer;
}
```
The `Util.isBlank()` does the null check so this can't be null.

So the other possibility for x86 is:
```java
cpuVendor = SysctlUtil.sysctl("machdep.cpu.vendor", "");
```
The default if the `sysctl` call fails is an empty string.  So the only possibility here is if the call succeeded and we got a null return.  This code passes a pointer to a buffer and calls JNA with `return p.getString(0)`. I've traced the code there and don't see how that can be null either.

Furthermore, even if the argument passed in was `null`, it would have NPE'd in the constructor here:

https://github.com/oshi/oshi/blob/c43e7588ee13f2907dcff5ef2b176268a4d774be/oshi-core/src/main/java/oshi/hardware/CentralProcessor.java#L678C13-L678C100

or further down:

https://github.com/oshi/oshi/blob/c43e7588ee13f2907dcff5ef2b176268a4d774be/oshi-core/src/main/java/oshi/hardware/CentralProcessor.java#L688

So we have:
 - a non-null `final` field
 - somehow becoming `null` later

That's generally impossible without reflection or similar.

Anyone have any other ideas?

**Comment by dbwiddis** [comment]
AHHHH, now I get it.

The problem IS indeed this call:

https://github.com/oshi/oshi/blob/c43e7588ee13f2907dcff5ef2b176268a4d774be/oshi-core/src/main/java/oshi/hardware/CentralProcessor.java#L678

`this.cpuVendor` is still null while calling this, but when `cpuVendor` starts with "0x" it delegates here:

https://github.com/oshi/oshi/blob/c43e7588ee13f2907dcff5ef2b176268a4d774be/oshi-core/src/main/java/oshi/hardware/CentralProcessor.java#L860-L864

If that check for vendor fails it tries to default back to the original "0x" version... but defaults to the (still null/unassigned) field.  I think that's undefined behavior!

That's a bug introduced in  6.4.5, can mitigate by lowering version to 6.4.4, or upgrading to the new version I will release very shortly.

**Comment by dbwiddis** [comment]
It would be interesting to know what the vendor string was/is for that system, as it's not a typical "Apple" string nor is it in this list as 0x61:

https://github.com/oshi/oshi/blob/0e45b3fdbda95888540ad27c707e3aa641a4a46a/oshi-core/src/main/resources/oshi.architecture.properties#L3-L20

**Comment by alexstaeding** [comment]
I tested with a simple program:

```kt
fun main() = println(oshi.SystemInfo().hardware.processor)
```

Bare metal:
```
Apple M2 Max
 1 physical CPU package(s)
 12 physical CPU core(s) (8 performance + 4 efficiency)
 12 logical CPU(s)
Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
ProcessorID: 0100000cda33d83d
Microarchitecture: ARM64 SoC: Avalanche + Blizzard
```

In Docker container (with extra VM layer):
```

2023-11-24T23:19:18.268395464Z  1 physical CPU package(s)
2023-11-24T23:19:18.268397673Z  12 physical CPU core(s)
2023-11-24T23:19:18.268401006Z  12 logical CPU(s)
2023-11-24T23:19:18.268402256Z Identifier: 0x00 Family 8 Model 0x000 Stepping r0p0
2023-11-24T23:19:18.268403464Z ProcessorID: 0008000000000000
2023-11-24T23:19:18.268404631Z Microarchitecture: unknown
```

Should I test something else?

**Comment by dbwiddis** [comment]
Nope, this is good. 

> Identifier: 0x00 Family 8 Model 0x000 Stepping r0p0

The 0x00 for hardware implementer triggered the bug.  

Thanks for the test!
