### ISSUE TITLE
NoClassDefFoundError,use window,

### ISSUE THREAD

**Issue by 13276965576** [oshi/oshi#2571]
Exception in thread "upload-server-info" java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/VersionHelpers
	at oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:94)
	at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:82)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:76)
	at com.yeastar.cloud.dm.cluster.common.helper.OshiHelper.<clinit>(OshiHelper.java:34)
	at com.yeastar.cloud.dm.cluster.server.service.ServerService.uploadServerInfo(ServerService.java:344)
	at com.yeastar.cloud.dm.cluster.server.service.ServerService.lambda$initUploadServerInfoThread$0(ServerService.java:103)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.win32.VersionHelpers
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more
	
	
maven repository 

        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>6.4.11</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.14.0</version>
        </dependency>
   how can i do foy my application

**Comment by dbwiddis** [comment]
`VersionHelpers` is in the `jna-platform` dependency.  OSHI includes that transitively but you may have an older version from some other dependency.  Use `mvn dependency:tree`.

https://github.com/oshi/oshi/blob/master/src/site/markdown/FAQ.md#how-do-i-resolve-jna-noclassdeffounderror-or-nosuchmethoderror-issues

**Comment by 13276965576** [comment]
thk，its run.
