### ISSUE TITLE
Questions encountered when using Java 17

### ISSUE THREAD

**Issue by ShangChilde** [oshi/oshi#2584]
Hello big shot, I have a problem and would like to see your thoughts。
My development environment is..
java version：17
SpringBoot : 3.2.1
maven:
` <dependency>
    <groupId>com.github.oshi</groupId>
    <artifactId>oshi-core</artifactId>
    <version>6.4.12</version>
</dependency>`
Some of the codes are as follows
` public static CpuInfo getCpu() {
        CpuInfo cpu = new CpuInfo();
        SystemInfo si = new SystemInfo();
        HardwareAbstractionLayer hal = si.getHardware();
        setCpuInfo(hal.getProcessor(), cpu);
        MemInfo memInfo = setMemInfo(hal.getMemory());
        cpu.setMemInfo(memInfo);
        setSysInfo(cpu);
        setJvmInfo(cpu);
        setSysFiles(si.getOperatingSystem(), cpu);
        return cpu;
    }

    public static void main(String[] args) {
        getCpu();
    }
`
At this point, an exception occurred as follows
`xception in thread "main" java.lang.AbstractMethodError: Receiver class com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX does not define or inherit an implementation of the resolved method 'abstract java.util.List getFieldOrder()' of abstract class com.sun.jna.Structure.
	at com.sun.jna.Structure.fieldOrder(Structure.java:952)
	at com.sun.jna.Structure.getFields(Structure.java:1006)
	at com.sun.jna.Structure.deriveLayout(Structure.java:1172)
	at com.sun.jna.Structure.calculateSize(Structure.java:1097)
	at com.sun.jna.Structure.calculateSize(Structure.java:1049)
	at com.sun.jna.Structure.allocateMemory(Structure.java:403)
	at com.sun.jna.Structure.<init>(Structure.java:194)
	at com.sun.jna.Structure.<init>(Structure.java:182)
	at com.sun.jna.Structure.<init>(Structure.java:169)
	at com.sun.jna.Structure.<init>(Structure.java:161)
	at com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX.<init>(WinNT.java:1980)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:59)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindows8OrGreater(VersionHelpers.java:170)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<clinit>(WindowsCentralProcessor.java:70)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:42)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)`

**Comment by ShangChilde** [comment]
Thank you for answering other issues. I have resolved the issue because there are already JNA related dependencies in other dependencies

**Comment by dbwiddis** [comment]
> Receiver class com.sun.jna.platform....  does not define or inherit an implementation of t... abstract class com.sun.jna. ...

I see you've already resolved this.  You had version 5.x of the jna-platform dependency but 4.x of the jna dependency. :)

**Comment by ShangChilde** [comment]
Thank you for answering other issues. I have resolved the issue because there are already JNA related dependencies in other dependencies

**Comment by ShangChilde** [comment]
Thank you for answering other issues. I have resolved the issue because there are already JNA related dependencies in other dependencies
