### ISSUE TITLE
Error running my program in Linux - Unable to load library 'udev'. It runs on Windows just fine.

### ISSUE THREAD

**Issue by pkanthi** [oshi/oshi#271]
Hi There,

I am using OSHI maven repos as suggested. I am running SystemInfoTest sample by copying it into my env. The program works great in Windows. It fails in Linux where it tries to get Disk info. Following is the exception... 

[2016-11-20 23:33:09,093] [ INFO] (SystemInfoTest.java:59) - Checking Disks...
[2016-11-20 23:33:09,096] [DEBUG] (FileUtil.java:71) - Reading file /proc/self/mounts
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'udev': Native library (linux-x86/libudev.so) not found in resource path ([rsrc:./, jar:rsrc:oshi-core-3.2.jar!/, jar:rsrc:jersey-client-1.18.3.jar!/, jar:rsrc:jersey-core-1.18.3.jar!/, jar:rsrc:log4j-1.2.16.jar!/, jar:rsrc:json-20141113.jar!/, jar:rsrc:jna-4.2.2.jar!/, jar:rsrc:slf4j-log4j12-1.7.12.jar!/, jar:rsrc:slf4j-api-1.7.12.jar!/, jar:rsrc:jna-platform-4.2.2.jar!/])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
	at oshi.jna.platform.linux.Udev.<clinit>(Udev.java:33)
	at oshi.hardware.platform.linux.LinuxDisks.getDisks(LinuxDisks.java:66)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getDiskStores(LinuxHardwareAbstractionLayer.java:70)
	at com.testing.SystemInfoTest.main(SystemInfoTest.java:60)
	... 5 more

I did install libudev with 'yum install libudev'. My system is x86_64 though - (Linux testhost 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux). I see from exception that it is looking for linux-x86/libudev.so. Not sure if that is an issue. I do have udev shared library in the filesystem (check below).

lrwxrwxrwx 1 root root    16 Nov 20 22:47 /lib64/libudev.so.0 -> libudev.so.0.5.1
-rwxr-xr-x 1 root root 55184 Sep  6 09:51 /lib64/libudev.so.0.5.1

I would appreciate the help.

Prakash

**Comment by dbwiddis** [comment]
This is a bit out of my league as it's more of a JNA question than OSHI-specific.  However, I think this link may be helpful:  http://stackoverflow.com/questions/32988071/java-lang-unsatisfiedlinkerror-unable-to-load-library

**Comment by dbwiddis** [comment]
Were you able to get this resolved?

**Comment by akoshpinter** [comment]
I have a similar issue, it seems that CentOS (and RHEL) do not have that library... So JSON cannot be generated in that case...

**Comment by dbwiddis** [comment]
Yes, I can catch the error and return an empty disk array if necessary -- and I'll do so this week (3.3 release planned for the New Year.)  However, that's attacking the symptom and not the problem.

I had thought any linux distribution ought to be able to add `libudev`.   The OP's question was geared more towards having added it and having JNA unable to find it, which I think is an issue outside OSHI.

Is libudev not available for RHEL or CentOS?   Do these systems have sysfs, which I can mine for the same information (libudev is just a much friendlier front-end to sysfs)?

**Comment by dbwiddis** [comment]
I believe this issue should be resolvable for users with two steps:

1. Install libudev: http://rpm.pbone.net/index.php3/stat/3/srodzaj/1/search/pkgconfig(libudev)
2. If necessary, add the new libudev location to System Property `java.library.path`, e.g.,
```
System.setProperty("java.library.path", "/lib64;" 
              + System.getProperty("java.library.path"));
```

I'll still try to catch the exception and log an error, but let me know if the above steps don't fix it so I can look for a longer term workaround.

**Comment by akoshpinter** [comment]
Hi, thanks for the reply!

I stand corrected, there is no precompiled package of libudev (or libudev-devel) for CentOS 5... We definitely want to upgrade that machine, it is quite outdated.

On another CentOS 6 machine, installing libudev-devel resolved the issue.

**Comment by dbwiddis** [comment]
Given that the error is clear enough to point to a solution, and that this is a dependency for multiple hardware (disks, usb) and that it can be effectively worked around for older OS's by not calling the associated methods (or suppressing them in json) I think I'll just leave this as-is.

**Comment by Anonymenus** [comment]
I got this problem as well. The `JNA version` is `5.8`, The `glibc version` is `2.14.1`, the `udev version` is `147`, I don't know if it is  the lower-version plugin caused this problem.
