### ISSUE TITLE
Unable to access `GlobalMemory` object while fetching memory information in Mac device using maven library

### ISSUE THREAD

**Issue by iumairhasan** [oshi/oshi#2758]
## Description
I'm trying to gather memory, cpu, and network metrics on my device. I was planning to use Oshi library for that. But while testing this library, I'm running into `java.lang.NoSuchMethodError` error while accessing memory metrics. Additionally I think Im unable to access objects from `hardwareInfo`.

I looked into README, and it looks like SystemInfo is getting initialize as expected ([SystemInfoTest.java#L84](https://github.com/oshi/oshi/blob/master/oshi-core/src/test/java/oshi/SystemInfoTest.java#L84)).

* Can someone help me with whats wrong in my code? or any guidance on using this library.

## Maven library 
* I'm using `6.6.5` version of oshi maven library
```
        <!-- https://mvnrepository.com/artifact/com.github.oshi/oshi-core -->
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>6.6.5</version>
        </dependency>
```

### Code
```
public class HostInfoMain {
    private static final String OUTPUT_FORMAT = "%s-%s";

    public static void main(String[] args) {

        SystemInfo systemInfo = new SystemInfo();
        HardwareAbstractionLayer hardwareInfo = systemInfo.getHardware();
        GlobalMemory memoryInfo = hardwareInfo.getMemory();
        VirtualMemory virtualMemoryInfo = memoryInfo.getVirtualMemory();

        System.out.println(OUTPUT_FORMAT.formatted("SystemInfo Version", systemInfo.getClass().getPackage().getImplementationVersion()));
        System.out.println(OUTPUT_FORMAT.formatted("HardwareAbstractionLayer Version", systemInfo.getClass().getPackage().getImplementationVersion()));
        System.out.println(OUTPUT_FORMAT.formatted("GlobalMemory Version", memoryInfo.getClass().getPackage().getImplementationVersion()));
        System.out.println(OUTPUT_FORMAT.formatted("VirtualMemory Version", virtualMemoryInfo.getClass().getPackage().getImplementationVersion()));

        System.out.println(OUTPUT_FORMAT.formatted("systemInfo", systemInfo));
        System.out.println(OUTPUT_FORMAT.formatted("hardwareInfo", hardwareInfo));
        System.out.println(OUTPUT_FORMAT.formatted("memoryInfo", hardwareInfo.getMemory()));

        System.out.println("----------");
    }
}
```

### Output
```
SystemInfo Version-6.6.5
HardwareAbstractionLayer Version-6.6.5
GlobalMemory Version-6.6.5
VirtualMemory Version-6.6.5
systemInfo-oshi.SystemInfo@14899482
hardwareInfo-oshi.hardware.platform.mac.MacHardwareAbstractionLayer@21588809
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.sun.jna.Memory.close()'
	at oshi.util.Util.freeMemory(Util.java:83)
	at oshi.jna.ByRef$CloseableLongByReference.close(ByRef.java:52)
	at oshi.hardware.platform.mac.MacGlobalMemory.queryPageSize(MacGlobalMemory.java:146)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.platform.mac.MacGlobalMemory.getPageSize(MacGlobalMemory.java:60)
	at oshi.hardware.platform.mac.MacGlobalMemory.queryVmStats(MacGlobalMemory.java:133)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.platform.mac.MacGlobalMemory.getAvailable(MacGlobalMemory.java:50)
	at oshi.hardware.common.AbstractGlobalMemory.toString(AbstractGlobalMemory.java:98)
	at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3056)
	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2933)
	at java.base/java.util.Formatter.format(Formatter.java:2689)
	at java.base/java.util.Formatter.format(Formatter.java:2625)
	at java.base/java.lang.String.formatted(String.java:4207)
	at org.example.hostmetrics.HostInfoMain.main(HostInfoMain.java:27)
	Suppressed: java.lang.NoSuchMethodError: 'void com.sun.jna.Memory.close()'
		at oshi.util.Util.freeMemory(Util.java:83)
		at oshi.jna.ByRef$CloseableIntByReference.close(ByRef.java:37)
		at oshi.hardware.platform.mac.MacGlobalMemory.queryVmStats(MacGlobalMemory.java:126)
		... 9 more
	Suppressed: java.lang.NoSuchMethodError: 'void com.sun.jna.Memory.close()'
		at oshi.util.Util.freeMemory(Util.java:83)
		at oshi.jna.Struct$CloseableVMStatistics.close(Struct.java:85)
		at oshi.hardware.platform.mac.MacGlobalMemory.queryVmStats(MacGlobalMemory.java:126)
		... 9 more

Process finished with exit code 1

```

Thanks,
Umair

**Comment by dbwiddis** [comment]
> Exception in thread "main" java.lang.NoSuchMethodError: 'void com.sun.jna.Memory.close()'

You probably don't have the current JNA dependency.

See https://github.com/oshi/oshi/blob/master/src/site/markdown/FAQ.md#how-do-i-resolve-jna-noclassdeffounderror-or-nosuchmethoderror-issues

**Comment by iumairhasan** [comment]
Perfect! I needed to add updated jna in my pom file to resolve this! Thank you for the quick response

https://mvnrepository.com/artifact/net.java.dev.jna/jna
https://mvnrepository.com/artifact/net.java.dev.jna/jna-platform
