### ISSUE TITLE
Maven test build shows WARN and ERROR messages

### ISSUE THREAD

**Issue by ckadner** [oshi/oshi#299]
I just cloned the `oshi` repository and ran a full maven build `mvn clean package`. At the end of the build it showed all tests completed successfully, yet there were various warnings and errors:

**Errors/Warnings from Maven Test (STDERR)**
```
[oshi]$ mvn test -q 1> /dev/null

[main] WARN oshi.util.FileUtil - File not found: does/not/exist
[main] WARN oshi.util.FormatUtil - Date parse error: java.time.format.DateTimeParseException: Text 'Unparseable' could not be parsed at index 0
[main] WARN oshi.util.ParseUtil - Invalid hexadecimal string: expected error abcde
[main] WARN oshi.util.ParseUtil - Invalid hexadecimal string: abcde
[main] ERROR oshi.json.util.PropertiesUtil - No properties file does.not.exist on the classpath.
[main] ERROR oshi.json.util.PropertiesUtil - Property value 5 from property operatingSystem.processes.limit does not match enum class oshi.software.os.OperatingSystem$ProcessSort. {}
java.lang.IllegalArgumentException: No enum constant oshi.software.os.OperatingSystem.ProcessSort.5
        at java.lang.Enum.valueOf(Enum.java:238)
        at oshi.json.util.PropertiesUtil.getEnum(PropertiesUtil.java:126)
        at oshi.json.util.PropertiesUtilTest.testLoadProperties(PropertiesUtilTest.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

**Full Test Log (STDOUT & STDERR)**
```
[oshi]$ mvn test -q
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
objc[30872]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Running oshi.hardware.CentralProcessorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.832 sec - in oshi.hardware.CentralProcessorTest
Running oshi.hardware.ComputerSystemTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.182 sec - in oshi.hardware.ComputerSystemTest
Running oshi.hardware.DisksTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.144 sec - in oshi.hardware.DisksTest
Running oshi.hardware.DisplayTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in oshi.hardware.DisplayTest
Running oshi.hardware.GlobalMemoryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in oshi.hardware.GlobalMemoryTest
Running oshi.hardware.NetworksTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 sec - in oshi.hardware.NetworksTest
Running oshi.hardware.PowerSourceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in oshi.hardware.PowerSourceTest
Running oshi.hardware.SensorsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.067 sec - in oshi.hardware.SensorsTest
Running oshi.hardware.UsbDeviceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in oshi.hardware.UsbDeviceTest
Running oshi.software.os.FileSystemTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in oshi.software.os.FileSystemTest
Running oshi.software.os.OperatingSystemTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.141 sec - in oshi.software.os.OperatingSystemTest
Running oshi.util.EdidUtilTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in oshi.util.EdidUtilTest
Running oshi.util.ExecutingCommandTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec - in oshi.util.ExecutingCommandTest
Running oshi.util.FileUtilTest
[main] WARN oshi.util.FileUtil - File not found: does/not/exist
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 sec - in oshi.util.FileUtilTest
Running oshi.util.FormatUtilTest
[main] WARN oshi.util.FormatUtil - Date parse error: java.time.format.DateTimeParseException: Text 'Unparseable' could not be parsed at index 0
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec - in oshi.util.FormatUtilTest
Running oshi.util.ParseUtilTest
[main] WARN oshi.util.ParseUtil - Invalid hexadecimal string: expected error abcde
[main] WARN oshi.util.ParseUtil - Invalid hexadecimal string: abcde
Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 sec - in oshi.util.ParseUtilTest
Running oshi.util.UtilTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.303 sec - in oshi.util.UtilTest

Results :
Tests run: 49, Failures: 0, Errors: 0, Skipped: 0

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
objc[30884]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Running oshi.json.hardware.CentralProcessorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.995 sec - in oshi.json.hardware.CentralProcessorTest
Running oshi.json.hardware.ComputerSystemTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.211 sec - in oshi.json.hardware.ComputerSystemTest
Running oshi.json.hardware.DisksTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.138 sec - in oshi.json.hardware.DisksTest
Running oshi.json.hardware.DisplayTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in oshi.json.hardware.DisplayTest
Running oshi.json.hardware.GlobalMemoryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in oshi.json.hardware.GlobalMemoryTest
Running oshi.json.hardware.NetworksTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.048 sec - in oshi.json.hardware.NetworksTest
Running oshi.json.hardware.PowerSourceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 sec - in oshi.json.hardware.PowerSourceTest
Running oshi.json.hardware.SensorsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.217 sec - in oshi.json.hardware.SensorsTest
Running oshi.json.hardware.UsbDeviceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in oshi.json.hardware.UsbDeviceTest
Running oshi.json.json.NullAwareJsonObjectBuilderTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.041 sec - in oshi.json.json.NullAwareJsonObjectBuilderTest
Running oshi.json.software.os.FileSystemTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 sec - in oshi.json.software.os.FileSystemTest
Running oshi.json.software.os.OperatingSystemTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.192 sec - in oshi.json.software.os.OperatingSystemTest
Running oshi.json.SystemInfoTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.884 sec - in oshi.json.SystemInfoTest
Running oshi.json.util.PropertiesUtilTest
[main] ERROR oshi.json.util.PropertiesUtil - No properties file does.not.exist on the classpath.
[main] ERROR oshi.json.util.PropertiesUtil - Property value 5 from property operatingSystem.processes.limit does not match enum class oshi.software.os.OperatingSystem$ProcessSort. {}
java.lang.IllegalArgumentException: No enum constant oshi.software.os.OperatingSystem.ProcessSort.5
        at java.lang.Enum.valueOf(Enum.java:238)
        at oshi.json.util.PropertiesUtil.getEnum(PropertiesUtil.java:126)
        at oshi.json.util.PropertiesUtilTest.testLoadProperties(PropertiesUtilTest.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in oshi.json.util.PropertiesUtilTest

Results :
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by hazendaz** [comment]
Nice fix.  I need to do same elsewhere.

Get Outlook for Android<https://aka.ms/ghei36>



On Sat, Jan 14, 2017 at 11:04 AM -0500, "dbwiddis" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #299<https://github.com/oshi/oshi/issues/299> via 15ee453<https://github.com/oshi/oshi/commit/15ee45381b8660937f5d79bf55d71091ec05d8d2>.

**Comment by dbwiddis** [comment]
So, I accepted this fix and think it's great to suppress for the actual test output.

However, while testing/debugging new code I like to run `SystemInfoTest`'s `main()` method (as a Java program, not as a Junit test) and would like to see the errors then... I don't.   Is this an easy modification to your existing fix?

**Comment by ckadner** [comment]
@dbwiddis  my fix in [PR#300](https://github.com/oshi/oshi/pull/300/files) only affects test execution (mvn test scope). 
So if you run your adhoc tests using Java from the command line or with `mvn exec:java` then the logging behavior should be unaffected.
If for some reason the `simplelogger.properties` file gets picked up in the classpath (i.e. if you include the `target/test-classes` folder in the classpath) then you could modify that `simplelogger.properties` to change the log thresholds and then we can figure out next steps :-)

```
# don't show expected errors during test execution
org.slf4j.simpleLogger.log.oshi.util=ERROR            # change this
```

```
# don't show expected errors during test execution
org.slf4j.simpleLogger.log.oshi.json.util=OFF         # change this
``` 
Could you eleborate on how you run your adhoc tests and paste the commands you run?

**Comment by dbwiddis** [comment]
I simply run them from Eclipse IDE using "Run as Java Application".   Behind the scenes it runs java command line:

> /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:62106 -Dfile.encoding=UTF-8 -classpath /Users/danielwiddis/git/oshi/oshi-json/target/test-classes:/Users/danielwiddis/git/oshi/oshi-json/target/classes:/Users/danielwiddis/git/oshi/oshi-core/target/classes:/Users/danielwiddis/git/oshi/oshi-core/target/test-classes:/Users/danielwiddis/.m2/repository/net/java/dev/jna/jna-platform/4.2.2/jna-platform-4.2.2.jar:/Users/danielwiddis/.m2/repository/net/java/dev/jna/jna/4.2.2/jna-4.2.2.jar:/Users/danielwiddis/.m2/repository/org/slf4j/slf4j-api/1.7.22/slf4j-api-1.7.22.jar:/Users/danielwiddis/.m2/repository/org/slf4j/slf4j-simple/1.7.22/slf4j-simple-1.7.22.jar:/Users/danielwiddis/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/danielwiddis/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/danielwiddis/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar oshi.json.SystemInfoTest

One quick possibility might be programmatically turning `org.slf4j.simpleLogger.log.oshi.json.util` back on from inside the SystemInfoTest main method, thus overriding the value it gets from the classpath.

**Comment by dbwiddis** [comment]
Hm. Looks like I'm already programmatically updating the log level inside those `main()` methods:
`System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "INFO");`

I may just need to also do that specifically for the util class that got suppressed.  Will try that.

**Comment by dbwiddis** [comment]
Aha.   It's logging, just to another file.   Problem solved by adding:
`        System.setProperty(org.slf4j.impl.SimpleLogger.LOG_FILE_KEY, "System.out");
`

**Comment by ckadner** [comment]
I see, since you are running a class under `src/test` Eclipse makes all test-classes and test resources available in the classpath.

If I understand the purpose of the two `SystemInfoTest` classes correctly, the these are somewhat inbetween traditional scopes of production code and test code. You don't want them to end up in the released binary artifacts so they should not live under `src/main` -- yet they are not strictly speaking tests so they are not perfectly situated under `src/test` either. 

So I think programmatically changing the logger settings is legitimate. I would not recommend writing INFO messages to the same console which displays the actual system information that users are interested in. Instead I would recommend to log messages to another file or at least use `System.err` for log messages and `System.out` for the actual system report information. That way users could pipe log messages to a file via the stderr file descriptor like:

```Shell
$ mvn test-compile -pl oshi-core -q exec:java \
   -Dexec.mainClass="oshi.SystemInfoTest" \
   -Dexec.classpathScope="test" 2> test.log

```

**Comment by dbwiddis** [comment]
Brilliant suggestion to use `System.err`.  That restores the behavior to what I think was the default behavior.

You're correct, the `SystemInfoTest` are not really test classes. They're "demo" classes that I frequently use to visually test for "sane" output as I port to various systems (and debug my inevitable mistakes).  

The general use case for users is that they would copy/edit this code in their own applications.

I've committed the `System.err` version and am rather happy with this solution.  Thanks again.
