### ISSUE TITLE
NoSuchMethodError com.sun.jna.platform.mac.SystemB$VMStatistics.createFieldsOrder

### ISSUE THREAD

**Issue by henry1992007** [oshi/oshi#344]
NoSuchMethodError is thrown when execute new SystemInfo().getHardware().getMemory() @oshi 3.4.2
```
java.lang.NoSuchMethodError: com.sun.jna.platform.mac.SystemB$VMStatistics.createFieldsOrder([Ljava/lang/String;)Ljava/util/List;
  at com.sun.jna.platform.mac.SystemB$VMStatistics.<clinit>(SystemB.java:90)
  at oshi.hardware.platform.mac.MacGlobalMemory.<init>(MacGlobalMemory.java:48)
  at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getMemory(MacHardwareAbstractionLayer.java:64)
  at com.koubei.cavalry.core.log.SystemInfo.<clinit>(SystemInfo.java:40)
  at com.koubei.cavalry.core.log.SystemLogger.log(SystemLogger.java:20)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
  at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

i am developing on macOS 10.12.3 
please help, thanks very much

**Comment by dbwiddis** [comment]
Do you have all the appropriate dependencies in your project (jna and jna-platform)?

**Comment by henry1992007** [comment]
the only dependency in my pom.xml that has to do with oshi is
```
<dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>3.4.2</version>
</dependency>
```
that's all
so do i need to add any other extra dependencies ?

**Comment by henry1992007** [comment]
btw oshi 3.4.0 works fine

**Comment by dbwiddis** [comment]
Maven should take care of the transitive dependencies, but your error indicates Java is looking for a method introduced in JNA 4.3.0 and not finding it.  OSHI 3.4.0 required JNA 4.2.2 and is therefore not giving you the error.   How are you building?   Can you use `mvn clean` to get rid of any old versions of dependencies?

**Comment by henry1992007** [comment]
i have tried `mvn clean` but that won't work

i deleted the jna and the jna-platform dependencies in my local .m2 repo and let maven resolve them itself again
 
and i got jna 4.2.2 and jna-platform 4.3.0

**Comment by henry1992007** [comment]
you may need to start up a clean project with just OSHI 3.4.2 depended yourself and call 
`new SystemInfo().getHardware().getMemory()`
to see if it is the problem with my project configuration or OSHI's dependencies 😄

**Comment by dbwiddis** [comment]
The `pom.xml` for jna-platform 4.3.0 depends on jna 4.3.0.  From the Central Repository:
```
<dependency>
  <groupId>net.java.dev.jna</groupId>
  <artifactId>jna</artifactId>
  <version>4.3.0</version>
</dependency>
```
You may have had metadata in your `.m2` repo that didn't register the deletion. Try just deleting the entire repository.

**Comment by henry1992007** [comment]
ok, i just output the dependency tree and found out that one of my dependency depend on jna-4.2.2.

everything works fine after i exclude it, thanks very much

**Comment by leefj** [comment]
Exception in thread "main" java.lang.NoSuchMethodError: oshi.jna.platform.mac.SystemB.mach_task_self()I

I have already add the JAN , why this error ?

**Comment by leefj** [comment]
fullstak:

Exception in thread "main" java.lang.NoSuchMethodError: oshi.jna.platform.mac.SystemB.mach_task_self()I
	at oshi.util.platform.mac.SmcUtil.smcOpen(SmcUtil.java:74)
	at oshi.hardware.platform.mac.MacSensors.<init>(MacSensors.java:47)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getSensors(MacHardwareAbstractionLayer.java:99)
	at com.fallout.common.utils.SystemInfoTest.main(SystemInfoTest.java:76)
