### ISSUE TITLE
oshi run over RedHat 5.5

### ISSUE THREAD

**Issue by jcpalma** [oshi/oshi#378]
Hi, I'm trying to run this library over RedHat 5.5 but it try an exception. 

Note: I can't update the OS because are critical and production plataforms.
Note: The program runs excellent over Windows Server.

May you help me?

```
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: /tmp/jna--1008861826/jna4196856076537055888.tmp: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/jna--1008861826/jna4196856076537055888.tmp)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
        at java.lang.Runtime.load0(Runtime.java:795)
        at java.lang.System.load(System.java:1062)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
        at com.sun.jna.Native.<clinit>(Native.java:190)
        at oshi.jna.platform.linux.Libc.<clinit>(Libc.java:38)
        at oshi.hardware.platform.linux.LinuxCentralProcessor.getSystemLoadAverage(LinuxCentralProcessor.java:219)
        at oshi.hardware.common.AbstractCentralProcessor.getSystemLoadAverage(AbstractCentralProcessor.java:447)
        at oshi.json.hardware.impl.CentralProcessorImpl.getSystemLoadAverage(CentralProcessorImpl.java:230)
        at oshi.json.hardware.impl.CentralProcessorImpl.toJSON(CentralProcessorImpl.java:343)
        at oshi.json.json.AbstractOshiJsonObject.toPrettyJSON(AbstractOshiJsonObject.java:67)
        at oshi.json.json.AbstractOshiJsonObject.toPrettyJSON(AbstractOshiJsonObject.java:58)
        at org.dwh.cell.utl.svc.Plataform.updateCPU(Plataform.java:34)
        at org.dwh.cell.utl.svc.Service.updateOS(Service.java:54)
        at org.dwh.cell.utl.svc.Service.update(Service.java:44)
        at org.dwh.cell.Neurona.run(Neurona.java:39)
```

**Comment by dbwiddis** [comment]
See #338.  It looks like this is probably related to updating JNA from 4.2.2 to 4.3.0 (with 4.4.0 planned for next release).  JNA now appears to require glibc version 2.14, but you may have a previous version.

See [here](https://github.com/java-native-access/jna/issues/771) 

Can you try an earlier version of OSHI (3.3) and see if the problem goes away?

Are you able to update glibc on your distribution?

**Comment by jcpalma** [comment]
Hello dbwiddis, thanks for you answer...
I tried to use version oshi-core 3.3 (with JNA 3.3) but netbeans tells me that it is compiled with JDK8, the problem for my case is that it is not so easy to request an update to the servers, either for operating system libraries or other applications (Java in this case) How can I compile it with JDK7 (which is the version that are currently on the servers)?

Note: I tried to use oshi-core4.3.2 (with JNA 3.3) it not work.
Note: oshi-core4.3.2 are compiled with JDK7, why oshi-core3.3 was compile with JDK8 :(

**Comment by YoshiEnVerde** [comment]
The switch from Java 7 to Java 8 was made for v2.5, and then we moved back to Java 7 for later versions.
There's only two ways to do this for your situation right now:

1. Use a version earlier than 2.5

2. Fork the current version, which runs in Java 7, and restore dependencies to an older version of JNA which is compatible with your target OS (That would be JNA 4.2.2 or older, as pointed by @dbwiddis )

The main problem is that some of the newer code in OSHI depends on JNA code that had critical bugs fixed on the latest few JNA patches, so it can't be ported back in the main stable version of the library

**Comment by YoshiEnVerde** [comment]
Outside of those two possibilities, you could also build your own copy of the latest JNA, under your target system, to ensure it will run on its glibc version.

This issue happened a whole major version ago, and the (the JNA implementers) rebuilt the stable version to depend on the older glibc v2.2.5 instead of the newer v2.11.

**This** would actually be your best bet (keeping the latest OSHI **and** JNA codes)

**Comment by jcpalma** [comment]
It's work!!! with oshi-core3.4.2 and both version for JNA. 
I'm using the two versions for JNA :smile: :smile: , because in ours Windows Servers only work JNA4.4.x and in Linux Servers only work JNA4.2.x

Thanks Yoshi & dbwiddis!
