### ISSUE TITLE
getProcessor NoSuchMethodError

### ISSUE THREAD

**Issue by david-zaletanski** [oshi/oshi#380]
When attempting to call HardwareAbstractionLayer.getProcessor() I am getting an error. This is using version 3.4.3 via Maven. Might be to do with Mac processor only based on call stack. Here is output of SystemInfoTest:

12:46:06.552 [main] INFO net.dzale.treeseeder.SystemInfoTest - Initializing System...
Apple macOS 10.12.5 (Sierra) build 16F73
12:46:07.062 [main] INFO net.dzale.treeseeder.SystemInfoTest - Checking computer system...
manufacturer: Apple Inc.
model: MacBook Pro (MacBookPro11,1)
serialnumber: C02P3MPYG3QH
firmware:
  manufacturer: Apple Inc.
  name: EFI
  description: unknown
  version: MBP111.0138.B25
  release date: unknown
baseboard:
  manufacturer: Apple Inc.
  model: SMC
  version: 2.16f68
  serialnumber: C02P3MPYG3QH
12:46:07.685 [main] INFO net.dzale.treeseeder.SystemInfoTest - Checking Processor...
12:46:07.702 [main] DEBUG oshi.hardware.common.AbstractCentralProcessor - Oracle MXBean detected.
Exception in thread "main" java.lang.NoSuchMethodError: com.sun.jna.platform.mac.SystemB$HostCpuLoadInfo.createFieldsOrder(Ljava/lang/String;)Ljava/util/List;
	at com.sun.jna.platform.mac.SystemB$HostCpuLoadInfo.<clinit>(SystemB.java:69)
	at oshi.hardware.platform.mac.MacCentralProcessor.getSystemCpuLoadTicks(MacCentralProcessor.java:112)
	at oshi.hardware.common.AbstractCentralProcessor.updateSystemTicks(AbstractCentralProcessor.java:407)
	at oshi.hardware.common.AbstractCentralProcessor.initTicks(AbstractCentralProcessor.java:146)
	at oshi.hardware.platform.mac.MacCentralProcessor.<init>(MacCentralProcessor.java:75)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getProcessor(MacHardwareAbstractionLayer.java:53)
	at net.dzale.treeseeder.SystemInfoTest.main(SystemInfoTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by david-zaletanski** [comment]
Nevermind - had to import JNA dependency manually to fix.
```
    <dependency>
        <groupId>net.java.dev.jna</groupId>
        <artifactId>jna</artifactId>
        <version>4.4.0</version>
    </dependency>
```
