### ISSUE TITLE
Could not initialize class com.sun.jna.Memory

### ISSUE THREAD

**Issue by martinko2009** [oshi/oshi#394]
When I use it in Windows, It works well. but when I use it in linux, it doesn't work.
I put oshi-core-3.4.3.jar, jna-4.4.0.jar, jna-platform-4.4.0.jar, slf4j-api-1.7.25.jar, slf4j-log4j12-1.7.25.jar,
threetenbp-1.3.5.jar into the webapps/xxx/WEB-INF/lib. But it still throws these errors.
```
[root]# rpm -qa|grep glibc
glibc-common-2.12-1.132.el6_5.2.x86_64
compat-glibc-2.5-46.2.x86_64
glibc-headers-2.12-1.132.el6_5.2.x86_64
glibc-devel-2.12-1.132.el6_5.2.x86_64
glibc-2.12-1.132.el6_5.2.i686
glibc-2.12-1.132.el6_5.2.x86_64
compat-glibc-headers-2.5-46.2.x86_64
```
**I set tomcat temp folder to be able to exec**
**drwxrwxrwx. 3 root root  4096 8月   1 14:52 temp**

I use jdk-7u71-linux-x64.tar.gz  ， tomcat: apache-tomcat-7.0.70

**Error Info:**
**when tomcat start , it display errors like below:**
```
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
        at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
        at oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:213)
```
**after tomcat runs,  the application runs , it display errors like below:**
```
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Memory
        at oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:213)
```

**Linux Info:**
```
# cat /proc/version 
Linux version 2.6.32-431.23.3.el6.x86_64 (mockbuild@x86-027.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Wed Jul 16 06:12:23 EDT 2014
```
**Code Info:**
```
OSProcess process = null;
int pid = Integer.parseInt(pidSet.iterator().next());
SystemInfo si = new SystemInfo();
OperatingSystem os = si.getOperatingSystem();
process = os.getProcess(pid);
long uptime1 = process.getUpTime();
long readBytes1 = process.getBytesRead();
long writeBytes1 = process.getBytesWritten();
Thread.sleep(3000);
process = os.getProcess(pid);
long uptime2 = process.getUpTime();
long readBytes2 = process.getBytesRead();
long writeBytes2 = process.getBytesWritten();
long ioReadUseInfo = (readBytes2 - readBytes1)*1000/(uptime2-uptime1);
long ioWriteUseInfo = (writeBytes2 - writeBytes1)*1000/(uptime2-uptime1);
System.out.println(Sigar.formatSize(ioReadUseInfo).trim());
System.out.println(Sigar.formatSize(ioWriteUseInfo).trim());
			
```

**Comment by trejkaz** [comment]
You've omitted the "Caused by", which would tell you what actually happened.

**Comment by martinko2009** [comment]
In the log file , there has not "Caused by" words.

**Comment by trejkaz** [comment]
From my experience, you get that error if some other error occurred in a static initialiser, such as a native library being missing, which is reported in the "cause" for the exception.

Something (implying Tomcat) might have "forgotten" to log the full stack trace. Or some earlier call to the class might have swallowed the exception, in which case the second call to it will not have the cause on it. If you can run under a debugger, it should be relatively easy to catch the first time an error occurs in the class. Just stick a breakpoint on one of the initialisation lines in the class.

**Comment by martinko2009** [comment]
I add some start param like this: -Djna.nosys=true -Djna.debug_load=true -Djna.debug_load.jna=true
there are the debug info like below:
```
Looking in classpath from WebappClassLoader
  context: /aaaa
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
java.net.URLClassLoader@70e8efc5
 for /com/sun/jna/linux-x86-64/libjnidispatch.so
Found library resource at jar:file:/home/tomcat/webapps/qarmonitor_agsaidreceiver/WEB-INF/lib/jna-4.4.0.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
Trying /home/tomcat/temp/jna-3506402/jna4858557745114029766.tmp
[aaaa][2017-08-01 13:27:41,389][ERROR][com.primeton.access.client.impl.skeleton.ServiceEngine:38] 
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
        at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
        at oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:213)
```

**Comment by martinko2009** [comment]
**I set tomcat temp folder to be able to exec**
**drwxr-xr-x. 3 root root  4096 aug 1st   1 14:52 temp**

**Comment by martinko2009** [comment]
```
[root]# rpm -qa|grep glibc
glibc-common-2.12-1.132.el6_5.2.x86_64
compat-glibc-2.5-46.2.x86_64
glibc-headers-2.12-1.132.el6_5.2.x86_64
glibc-devel-2.12-1.132.el6_5.2.x86_64
glibc-2.12-1.132.el6_5.2.i686
glibc-2.12-1.132.el6_5.2.x86_64
compat-glibc-headers-2.5-46.2.x86_64
```

**Comment by martinko2009** [comment]
I have solve it. Thank you.
