### ISSUE TITLE
Error log emitted from MacOperatingSystem.getProcesses()

### ISSUE THREAD

**Issue by brettwooldridge** [oshi/oshi#395]
After upgrading to the latest version, this error message started appearing in our logs on Mac OS X Sierra:
```
11:48:03,498 [MacOperatingSystem       ] ERROR - Failed syctl call: kern.procargs2, Error code: 22
```
If we breakpoint in the oshi code and print a stacktrace we get:
```
at oshi.software.os.mac.MacOperatingSystem.getCommandLine(MacOperatingSystem.java:219)
at oshi.software.os.mac.MacOperatingSystem.getProcess(MacOperatingSystem.java:191)
at oshi.software.os.mac.MacOperatingSystem.getProcesses(MacOperatingSystem.java:94)
at com.private.company.PerformanceSampler.run(PerformanceSampler.java:145)
...
at java.lang.Thread.run(Thread.java:748)
```
Digging a little deeper, the issue seems to be that when ``getProcess()`` is called from ``getProcesses()`` (line 94) with a ``pid`` value of ``0``, the error 22 (EINVAL) is raised:
```java
88    public OSProcess[] getProcesses(int limit, ProcessSort sort) {
89        List<OSProcess> procs = new ArrayList<>();
90        int[] pids = new int[this.maxProc];
91        int numberOfProcesses = SystemB.INSTANCE.proc_listpids(SystemB.PROC_ALL_PIDS, 0, pids, pids.length)
92                / SystemB.INT_SIZE;
93        for (int i = 0; i < numberOfProcesses; i++) {
94            OSProcess proc = getProcess(pids[i]);
95            if (proc != null) {
96                procs.add(proc);
97            }
98        }
99        ...
```

**Comment by dbwiddis** [comment]
by "latest version" do you mean OSHI or OS X?  Trying to narrow this down to what changed...
