### ISSUE TITLE
OOM: Java heap space

### ISSUE THREAD

**Issue by brettwooldridge** [oshi/oshi#420]
Only saw this once (so far), but it happened during server startup -- with -Xmx and -Xms set to 1.2G, so there is no way memory was actually exhausted.
```java
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.ArrayList.<init>(ArrayList.java:152) ~[?:1.8.0_111]
	at oshi.software.os.mac.MacOperatingSystem.getCommandLine(MacOperatingSystem.java:226) ~[oshi-core-3.4.3.jar:3.4.3]
	at oshi.software.os.mac.MacOperatingSystem.getProcess(MacOperatingSystem.java:191) ~[oshi-core-3.4.3.jar:3.4.3]
	at oshi.software.os.mac.MacOperatingSystem.getProcesses(MacOperatingSystem.java:94) ~[oshi-core-3.4.3.jar:3.4.3]
	at org.ziptie.zap.bootstrap.PerformanceSampler.run(PerformanceSampler.java:145) ~[com-dancer-zap-bootstrap.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.somepackage.GlobalTimerElf$LoggableScheduledFuture.invoke(GlobalTimerElf.java:176)
```
Judging from the error, I suspect some exceedingly large value was returned and oshi tried to allocate an enormous array.

Strangely, an immediate restart of the application did not encounter this error.  Nor had prior server starts, or have subsequent server starts.

Noteworthy is that the machine *was* just updated to High Sierra within the past 48 hours.

**Comment by dbwiddis** [comment]
I suspect this is related to #412, but I don't know if the fix (#415) will solve this.  We might need to add a sanity check for the return value....
