### ISSUE TITLE
Windows 10: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by phamtai93** [oshi/oshi#445]
I created new `OperatingSystem ` to get Operation System info
It worked perfectly on Ubuntu, but I got error as bellow when I try on Windows 10: 
```
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hal = si.getHardware();
OperatingSystem os = si.getOperatingSystem();
```

```
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.windows.WindowsOperatingSystem
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:180)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:112)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:104)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:69)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:317)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:255)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1166)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1158)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1055)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by dbwiddis** [comment]
This is almost always an issue with not having your dependencies defined correctly.  See #86, #338, #394.  Are you managing dependencies with Maven or downloading individual files?  Do you have duplicate jar files from different competing versions?

**Comment by NableLucas** [comment]
I have the same problem.
I import with this dependency
`
		<dependency>
			<groupId>com.github.oshi</groupId>
			<artifactId>oshi-core</artifactId>
			<version>3.4.4</version>
		</dependency>
`

My code is 
`
SystemInfo systemInfo = new SystemInfo();
OperatingSystem operatingSystem = systemInfo.getOperatingSystem();
`

My hardware informations 

![windows10](https://user-images.githubusercontent.com/16456458/36037359-b2b0bf7e-0da3-11e8-8c2e-69e8a940d3c5.png)

I use a notebook, in another pc with the same OS (Windows 10) it is ok

**Comment by dbwiddis** [comment]
The class definition is in the oshi files -- the only way this can't work is if the class isn't loaded properly.   Check how oshi (or the program it's embedded in) is called and if the classpath is correct; or if there is a conflicting/older version of oshi as a dependency in another part of the overall parent project.

**Comment by NableLucas** [comment]
I clear the folders in .m2 and i download again using maven

```
total 0
drwxr-xr-x 1 lnable 1049089 0 Feb 20 14:36 oshi-core/
drwxr-xr-x 1 lnable 1049089 0 Feb 20 14:36 oshi-parent/

./oshi-core:
total 4
drwxr-xr-x 1 lnable 1049089 0 Feb 20 14:36 3.4.0/

./oshi-core/3.4.0:
total 339
-rw-r--r-- 1 lnable 1049089    191 Feb 20 14:36 _remote.repositories
-rw-r--r-- 1 lnable 1049089 338636 Feb 20 14:36 oshi-core-3.4.0.jar
-rw-r--r-- 1 lnable 1049089     40 Feb 20 14:36 oshi-core-3.4.0.jar.sha1
-rw-r--r-- 1 lnable 1049089   1462 Feb 20 14:36 oshi-core-3.4.0.pom
-rw-r--r-- 1 lnable 1049089     40 Feb 20 14:36 oshi-core-3.4.0.pom.sha1

./oshi-parent:
total 0
drwxr-xr-x 1 lnable 1049089 0 Feb 20 14:36 3.4.0/

./oshi-parent/3.4.0:
total 34
-rw-r--r-- 1 lnable 1049089   165 Feb 20 14:36 _remote.repositories
-rw-r--r-- 1 lnable 1049089 29512 Feb 20 14:36 oshi-parent-3.4.0.pom
-rw-r--r-- 1 lnable 1049089    40 Feb 20 14:36 oshi-parent-3.4.0.pom.sha1

```

**Comment by dbwiddis** [comment]
Well, now it appears it's not getting your slf4j implementation...

**Comment by NableLucas** [comment]
Yes i am checking.

But the nullpointer in class WindowsOperatingSystem it is same.
 ```
	at oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:54)
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:92)
 ```

**Comment by spyhunter99** [comment]
working fine here

````
 <dependencies>
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>3.4.4</version>
        </dependency>

    </dependencies>
````

**Comment by dbwiddis** [comment]
Closing this as it's clearly a maven-related dependency issue, file list shows 3.4.0 but pom requests 3.4.4.
