### ISSUE TITLE
SystemInfo#getOperatingSystem in windows 10 enterprise  EN

### ISSUE THREAD

**Issue by langlichong** [oshi/oshi#497]
Exception in thread "main" java.lang.NoSuchMethodError: com.sun.jna.platform.win32.WinNT$PSID.createFieldsOrder(Ljava/lang/String;)Ljava/util/List;
	at com.sun.jna.platform.win32.WinNT$PSID.<clinit>(WinNT.java:354)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy0.<clinit>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739)
	at com.sun.jna.Native.loadLibrary(Native.java:506)

**Comment by dbwiddis** [comment]
Almost all "NoSuchMethodError" issues are caused by not having the correct JNA dependency included.  Are you using Maven or another dependency manager? What version of JNA is on your class path?

**Comment by langlichong** [comment]
i  just added the only one dependency  in gradle :    `compile 'com.github.oshi:oshi-core:3.5.0'` , is there JNA needed ?    i have no idea ,please help .

**Comment by dbwiddis** [comment]
Since you closed this, I assume you resolved it?
