### ISSUE TITLE
Invalid memory access getting network params

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#545]
The addition of `read()` after `super(p)` in the `IpHlpAPI` JNA file gives me this:

> Exception in thread "main" java.lang.Error: Invalid memory access
> 	at com.sun.jna.Native._getPointer(Native Method)
> 	at com.sun.jna.Native.getPointer(Native.java:2138)
> 	at com.sun.jna.Pointer.getPointer(Pointer.java:651)
> 	at com.sun.jna.Pointer.getValue(Pointer.java:376)
> 	at com.sun.jna.Structure.readField(Structure.java:720)
> 	at com.sun.jna.Structure.read(Structure.java:580)
> 	at com.sun.jna.Structure.autoRead(Structure.java:2074)
> 	at com.sun.jna.Structure.conditionalAutoRead(Structure.java:550)
> 	at com.sun.jna.Structure.updateStructureByReference(Structure.java:678)
> 	at com.sun.jna.Pointer.getValue(Pointer.java:376)
> 	at com.sun.jna.Structure.readField(Structure.java:720)
> 	at com.sun.jna.Structure.read(Structure.java:580)
> 	at oshi.jna.platform.windows.IPHlpAPI$FIXED_INFO.<init>(IPHlpAPI.java:219)
> 	at oshi.software.os.windows.WindowsNetworkParams.getDnsServers(WindowsNetworkParams.java:131)
> 	at oshi.software.os.NetworkParamsTest.testOperatingSystem(NetworkParamsTest.java:41)

I changed OSHI's code to conform to the [PR I submitted to the JNA project](https://github.com/java-native-access/jna/pull/983/files), where it passes the test case just fine.

So something's different in OSHI's implementation than the testcase (which I created a simplified version of OSHI's code for)...

**Comment by dbwiddis** [comment]
Running the testcase (or the OSHI method) by itself seems to work fine; the error occurs after repeated executions / memory management.

**Comment by dbwiddis** [comment]
The issue appears related to pointers to structures which have a (native) null value (e.g., 0) but are not actually null pointers.
