### ISSUE TITLE
java.lang.Error: Invalid memory access new SystemInfo().getOperatingSystem().getProcesses

### ISSUE THREAD

**Issue by Coalado** [oshi/oshi#615]
version: 3.8.0
`java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:419)
	at com.sun.jna.Function.invoke(Function.java:354)
	at com.sun.jna.Function.invoke(Function.java:308)
	at com.sun.jna.Function.invoke(Function.java:299)
	at com.sun.jna.Function.invokeInt(Function.java:707)
	at com.sun.jna.platform.win32.COM.COMInvoker._invokeNativeInt(COMInvoker.java:38)
	at com.sun.jna.platform.win32.COM.Unknown.Release(Unknown.java:80)
	at oshi.util.platform.windows.WmiUtil$WmiConnection.close(WmiUtil.java:138)
	at oshi.util.platform.windows.WmiUtil.closeStaleConnections(WmiUtil.java:249)
	at oshi.util.platform.windows.WmiUtil.connectToNamespace(WmiUtil.java:219)
	at oshi.util.platform.windows.WmiUtil.queryWMI(WmiUtil.java:167)
	at oshi.software.os.windows.WindowsOSVersionInfoEx.init(WindowsOSVersionInfoEx.java:57)
	at oshi.software.os.windows.WindowsOSVersionInfoEx.<init>(WindowsOSVersionInfoEx.java:50)
	at oshi.software.os.windows.WindowsOperatingSystem.<init>(WindowsOperatingSystem.java:120)
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:92)
....`

new SystemInfo().getOperatingSystem().getProcesses([pid])

This happens if I execute the code as a local system user account

**Comment by dbwiddis** [comment]
Try with the latest version.  The `WmiConnection` caching isn't even used any more (and it was obviously a bad idea.)

**Comment by dbwiddis** [comment]
Closing this as this issue has been fixed, and the code in the stack trace doesn't even exist any more. :)
