### ISSUE TITLE
CCE in WindowsNetworkParams.getIpv4DefaultGateway

### ISSUE THREAD

**Issue by retomerz** [oshi/oshi#616]
OSHI Version:
3.8.2

OS:
Microsoft Windows 10 build 17134

Exception:
```
java.lang.ClassCastException: ROUTEMETRIC is not a UINT32 type. CIM Type is 18 and VT type is 3
    at oshi.util.platform.windows.WmiUtil.getUint32(WmiUtil.java:314)
    at oshi.software.os.windows.WindowsNetworkParams.getNextHop(WindowsNetworkParams.java:152)
    at oshi.software.os.windows.WindowsNetworkParams.getIpv4DefaultGateway(WindowsNetworkParams.java:123)
```

**Comment by dbwiddis** [comment]
Already found and fixed that error in #614.  SNAPSHOT has the fix, and I'll probably push a patch release Friday.

**Comment by retomerz** [comment]
Thanks for the info. We will check it again when a new release is available.

**Comment by dbwiddis** [comment]
3.8.3 is released so this should be fixed.
