### ISSUE TITLE
java.lang.IllegalArgumentException: Structure exceeds provided memory bounds

### ISSUE THREAD

**Issue by lasselindqvist** [oshi/oshi#642]
Version: 3.8.4
OS: Windows 10 Pro that runs as a Jenkins slave

When trying to use WindowsOperatingSystem.getProcesses() to fetch the processes I get the following

```
 java.lang.IllegalArgumentException: Structure exceeds provided memory bounds
 	at com.sun.jna.Memory.boundsCheck(Memory.java:220)
 	at com.sun.jna.Memory$SharedMemory.boundsCheck(Memory.java:95)
 	at com.sun.jna.Memory.share(Memory.java:144)
 	at com.sun.jna.Structure.useMemory(Structure.java:342)
 	at com.sun.jna.Structure.<init>(Structure.java:191)
 	at com.sun.jna.Structure.<init>(Structure.java:182)
 	at com.sun.jna.Structure.<init>(Structure.java:178)
 	at oshi.jna.platform.windows.WinPerf$PERF_OBJECT_TYPE.<init>(WinPerf.java:137)
 	at oshi.software.os.windows.WindowsOperatingSystem.updateProcessMapFromRegistry(WindowsOperatingSystem.java:483)
 	at oshi.software.os.windows.WindowsOperatingSystem.processMapToList(WindowsOperatingSystem.java:294)
 	at oshi.software.os.windows.WindowsOperatingSystem.getProcesses(WindowsOperatingSystem.java:237)
```

The problem doesn't reproduce always though. It reproduces with both
os.getProcesses(0, ProcessSort.PID)
os.getProcesses(1024, ProcessSort.PID)
so the parameters probably don't matter.

**Comment by dbwiddis** [comment]
What happened here is that OSHI didn't reserve enough memory for the performance data block, probably due to a registry permissions issue.  The code in `WindowsOperatingSystem.java` doesn't check for an error code other than `ERROR_MORE_DATA` (to increase the buffer).    Fixing #643 should prevent this from even happening but it would be useful to add another error check here.

**Comment by dbwiddis** [comment]
Any chance you can instrument `WindowsOperatingSystem.java` to find out what error is returned in your case from the `Advapi32.INSTANCE.RegQueryValueEx()` call on line 150?  That's what we need to intercept and fail gracefully (with log error message about permissions.)

**Comment by lasselindqvist** [comment]
I can do that on Monday and let you know.

**Comment by dbwiddis** [comment]
I'll do some preliminary attempts to fix this over the weekend so hopefully on Monday you'll have an instrumented SNAPSHOT to test against.

**Comment by lasselindqvist** [comment]
I tried with the 3.9.0 and the logging is a bit funny when using English language:
`ERROR oshi.hardware.platform.windows.WindowsCentralProcessor - Unable to locate English counter names in registry Perflib 009. Assuming English counters.`

Other than that adding the user (In Computer management) to groups Performance Monitor Users and Performance Log Users and rebooting was enough. Some other functionalities might require and admin account though.

I think both of these can be closed unless some logging changes will be done.
