### ISSUE TITLE
oshi in maven repository version problem

### ISSUE THREAD

**Issue by jelly074100209** [oshi/oshi#657]
When I got the 3.9.0 version from maven repository, the jna version shoule be 4.5.2 according to .pom file. But actually I got the 4.2.2 version of jna, and cause the problem:
`Caused by: java.lang.NoSuchMethodError: com.sun.jna.platform.win32.OleAuto.VariantClear(Lcom/sun/jna/platform/win32/Variant$VARIANT;)Lcom/sun/jna/platform/win32/WinNT$HRESULT;
	at oshi.jna.platform.windows.WbemcliUtil$WmiQuery.enumerateProperties(WbemcliUtil.java:347)
	at oshi.jna.platform.windows.WbemcliUtil$WmiQuery.execute(WbemcliUtil.java:186)
	at oshi.util.platform.windows.WmiUtil.queryWMI(WmiUtil.java:136)
	at oshi.software.os.windows.WindowsOSVersionInfoEx.init(WindowsOSVersionInfoEx.java:55)
	at oshi.software.os.windows.WindowsOSVersionInfoEx.<init>(WindowsOSVersionInfoEx.java:49)
	at oshi.software.os.windows.WindowsOperatingSystem.<init>(WindowsOperatingSystem.java:120)
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:92)
	at com.bestarmedia.service.service.MonitorService.<init>(MonitorService.java:24)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 33 common frames omitted`

My maven is: 3.50
My OS is: windows 10

**Comment by jelly074100209** [comment]
@dbwiddis 
No. even though I try other oshi version, or run `mvn clean`, it still didn't work.

**Comment by dbwiddis** [comment]
What other dependencies does your project have?  As you note, the POM for OSHI includes the higher version so something else is causing the older dependency.

**Comment by dbwiddis** [comment]
Did you get this working?

**Comment by dbwiddis** [comment]
Since I haven't heard back from you, I'll assume it's working. I've double-checked the dependencies in the pom files and JNA versions packaged with the various downloads.  Feel free to re-open this issue if you need more help.
