### ISSUE TITLE
ExceptionIninitializationError from WindowsHardwareAbstractionLayer:82

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#661]
on oshi v3.8.4, windows7x64

java.lang.ExceptionInInitializerError
        at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getDiskStores(WindowsHardwareAbstractionLayer.java:82)
Caused by: java.lang.NullPointerException
        at oshi.util.platform.windows.PerfDataUtil.removeAllCounters(PerfDataUtil.java:227)
        at oshi.hardware.platform.windows.WindowsDisks.<clinit>(WindowsDisks.java:169)
        ... 8 more
00:43:44,471 WARN  [windows.PerfDataUtil] Failed to add PDH Counter: \System\Context Switches/sec, Error code: 0xC0000BB8
00:43:44,472 WARN  [windows.WindowsCentralProcessor] Unable to enumerate performance counter instances for .
Exception in thread "main" java.lang.NullPointerException
        at oshi.util.platform.windows.PerfDataUtil.removeAllCounters(PerfDataUtil.java:227)
        at oshi.hardware.platform.windows.WindowsCentralProcessor.initPdhCounters(WindowsCentralProcessor.java:246)
        at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:125)
        at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getProcessor(WindowsHardwareAbstractionLayer.java:64)

Any idea what's going on? It works fine on some computers but not on others

**Comment by dbwiddis** [comment]
Reported in #632.  Fixed in #634.  You might try the latest version. :)

**Comment by spyhunter99** [comment]
updating fix this, thanks!
