### ISSUE TITLE
CCE in WindowsSensors.getCpuVoltage

### ISSUE THREAD

**Issue by retomerz** [oshi/oshi#663]
OSHI Version:
3.9.0

OS:
Windows Server 2012 R2, 6.3 (Build 9600)

Exception:
```
java.lang.ClassCastException: CURRENTVOLTAGE is not a UINT32 type. CIM Type is 18 and VT type is 3
	at oshi.util.platform.windows.WmiUtil.getUint32(WmiUtil.java:283)
	at oshi.hardware.platform.windows.WindowsSensors.getCpuVoltage(WindowsSensors.java:258)
```

**Comment by dbwiddis** [comment]
Score 1 for verbose log messages that enforce strong typing.  Score 0 for not properly casting the UINT16.
