### ISSUE TITLE
SystemInfoTest fails for Sensors

### ISSUE THREAD

**Issue by HarshaKota** [oshi/oshi#708]
2018-12-04 15:59:09.614 [INFO] SystemInfoTest - Checking Sensors...
Sensors:
 CPU Temperature: 0.0°C
Exception in thread "main" java.lang.ClassCastException: DESIREDSPEED is not a UINT32 type. CIM Type is 21 and VT type is 1
	at oshi.util.platform.windows.WmiUtil.getUint32(WmiUtil.java:303)
	at oshi.hardware.platform.windows.WindowsSensors.getFanSpeeds(WindowsSensors.java:215)
	at oshi.SystemInfoTest.printSensors(SystemInfoTest.java:232)
	at oshi.SystemInfoTest.main(SystemInfoTest.java:105)

**Complete Output from SystemInfoTest testcase in oshi-core java test suite:**
https://pastebin.com/arJ8C1wB

**Comment by dbwiddis** [comment]
Looks like DesiredSpeed is a UINT64....
