### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/COM/WbemcliUtil$WmiQuery 

### ISSUE THREAD

**Issue by rigorio** [oshi/oshi#827]
I'm on a 64 bit Windows 10 laptop. Open JDK 11. I tried running:

```
  @Test
  public void testSoftware() {
    var si = new SystemInfo();
    System.out.println(si.getOperatingSystem().toString());
  }
```

It throws me this error:
```
java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/COM/WbemcliUtil$WmiQuery

	at oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:87)
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:92)
	at inc.pabacus.TaskMetrics.api.software.SoftwareServiceTest.testSoftware(SoftwareServiceTest.java:11)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.win32.COM.WbemcliUtil$WmiQuery
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 25 more
```
My dependencies:
```
    <dependency>
      <groupId>com.github.oshi</groupId>
      <artifactId>oshi-core</artifactId>
      <version>3.11.0</version>
    </dependency>
    <dependency>
      <groupId>com.1stleg</groupId>
      <artifactId>jnativehook</artifactId>
      <version>2.0.2</version>
    </dependency>
    <dependency>
      <groupId>net.java.dev.jna</groupId>
      <artifactId>jna</artifactId>
      <version>5.2.0</version>
    </dependency>
```

**Comment by dbwiddis** [comment]
You need both `jna` and the `jna-platform` dependencies.  You're getting those via OSHI with a transitive dependency, but since you're using `3.11.0` it's importing `jna-platform` version `5.1.0`.

**Comment by rigorio** [comment]
Hi thanks for replying. I apologize but while I do understand the problem I don't really know what to do specifically. Is there a set of maven dependencies that you would recommend I use in my pom.xml?

**Comment by dbwiddis** [comment]
Updating to the latest version of OSHI should work ... `3.13.0`.  Alternately (or at the same time) add a dependency to `jna-platform` version 5.2.0 the same way you've done for `jna`.

**Comment by rigorio** [comment]
Oh wow that does the job well. Thank you!

**Comment by ajferora** [comment]
I'm using 64 bit Windows 10. My dependency is 

		<dependency>
		    <groupId>com.github.oshi</groupId>
		    <artifactId>oshi-core</artifactId>
		    <version>4.6.1</version>
		</dependency>
and my jna transitive dependency version is 4.5.2. I'm getting this error:

Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/VersionHelpers
	at oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:110)
	at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:103)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:96)
	at com.company.ComputerIdentifier.getComputerIdentifier(ComputerIdentifier.java:36)
	at com.company.ComputerIdentifier.main(ComputerIdentifier.java:16)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.win32.VersionHelpers
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

What am I doing wrong?

**Comment by marioestrella** [comment]
I got it to work by making sure that jna and jna-platform was at the latest version of 5.5.0. 
Make sure to add the following to your pom:

```  
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.5.0</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>5.5.0</version>
        </dependency>
```


> I'm using 64 bit Windows 10. My dependency is
> 
> ```
> 	<dependency>
> 	    <groupId>com.github.oshi</groupId>
> 	    <artifactId>oshi-core</artifactId>
> 	    <version>4.6.1</version>
> 	</dependency>
> ```
> 
> and my jna transitive dependency version is 4.5.2. I'm getting this error:
> 
> Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/VersionHelpers
> at oshi.software.os.windows.WindowsOperatingSystem.(WindowsOperatingSystem.java:110)
> at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:103)
> at oshi.util.Memoizer$1.get(Memoizer.java:87)
> at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:96)
> at com.company.ComputerIdentifier.getComputerIdentifier(ComputerIdentifier.java:36)
> at com.company.ComputerIdentifier.main(ComputerIdentifier.java:16)
> Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.win32.VersionHelpers
> at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> ... 6 more
> 
> What am I doing wrong?

**Comment by dbwiddis** [comment]
Sorry, @ajferora I missed the question because it was on a closed issue.  OSHI 4.6.1 uses JNA 5.5.0 so you need to make sure you have the latest JNA version in your POM.  If you are inheriting a parent POM (e.g., Spring Boot) you need to override the properties of that parent file to make sure you have the right version.
