### ISSUE TITLE
Cannot gather hardware info with OpenJDK 11.

### ISSUE THREAD

**Issue by CaptainHillman** [oshi/oshi#834]
Trying to gather CPU information using the oshi-core dependancy (3.13.0) with OpenJDK (11.0.1, 64bit), but I'm getting some JNA errors. Is this something that's not yet supported or is there an issue/something I'm missing here?

Sample Code:
```
public class OshiTest {
    public static void main(String[] args) {
        SystemInfo systemInfo = new SystemInfo();
        HardwareAbstractionLayer hardwareInfo = systemInfo.getHardware();
        CentralProcessor cpu = hardwareInfo.getProcessor();
        
        System.out.println("Vendor: " + cpu.getVendor());
        System.out.println("Logical Cores: " + cpu.getLogicalProcessorCount());
        System.out.println("Frequency (Hz): " + cpu.getVendorFreq());
    }
}
```

Exception:
```
Exception in thread "main" java.lang.AbstractMethodError: Receiver class com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX does not define or inherit an implementation of the resolved method abstract getFieldOrder()Ljava/util/List; of abstract class com.sun.jna.Structure.
	at com.sun.jna.Structure.fieldOrder(Structure.java:952)
	at com.sun.jna.Structure.getFields(Structure.java:1006)
	at com.sun.jna.Structure.deriveLayout(Structure.java:1172)
	at com.sun.jna.Structure.calculateSize(Structure.java:1097)
	at com.sun.jna.Structure.calculateSize(Structure.java:1049)
	at com.sun.jna.Structure.allocateMemory(Structure.java:403)
	at com.sun.jna.Structure.<init>(Structure.java:194)
	at com.sun.jna.Structure.<init>(Structure.java:182)
	at com.sun.jna.Structure.<init>(Structure.java:169)
	at com.sun.jna.Structure.<init>(Structure.java:161)
	at com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX.<init>(WinNT.java:1929)
	at oshi.jna.platform.windows.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:56)
	at oshi.jna.platform.windows.VersionHelpers.IsWindowsVistaOrGreater(VersionHelpers.java:111)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<clinit>(WindowsCentralProcessor.java:65)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getProcessor(WindowsHardwareAbstractionLayer.java:70)
	at com.cmclinnovations.utils.intercom.elastic.OshiTest.main(OshiTest.java:20)
```

Happy to provide more details if required.
Thanks.

**Comment by dbwiddis** [comment]
This version of OSHI depends on JNA 5.2.0.  

The line numbers in the stack trace for JNA dependencies do not match the 5.2.0 release (e.g., [Structure.java:194](https://github.com/java-native-access/jna/blob/6ee6e42b91e64304590c075cfdf74ee71a9a974b/src/com/sun/jna/Structure.java#L194) in the stack trace appears to now be line 205.  This suggests you've got the wrong version of JNA dependency linked to your project.

Are you building via maven?

**Comment by CaptainHillman** [comment]
I am indeed, here's the relevant snippet from my POM:

```
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>  
            <version>3.13.0</version>
        </dependency>
        
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.2.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.26</version>
        </dependency>
```

**Comment by CaptainHillman** [comment]
I believe I've now resolved this. I'm not sure why, but including the Transport library from ElasticSearch causes some sort of conflict that produces the issue. For the time being, I've commented it out and all works as expected.

```
<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>transport</artifactId>
    <version>6.7.1</version>
</dependency
```

**Comment by dbwiddis** [comment]
Maven processes transitive dependencies in order.  It'll do all your top-level dependencies listed in your POM, and then start getting the dependencies of those packages, etc.

I suspect you have `transport` in your list prior to `oshi-core`, which results in the `transport` dependencies being included first.  While you also include `jna` at the top level (and thus get 5.2.0 there) you do not include `jna-platform` so it resolves to the first transitive dependency it finds in the list.

The solution (besides commenting out `transport`) is to rearrange your dependency list to include `oshi-core` before `transport`.  Alternately you could specify both `jna` and `jna-platform` in your own top-level POM to guarantee the version.  See #669.

**Comment by CaptainHillman** [comment]
I can confirm that you're correct; changing the order of dependancies as suggested resolves the issue.
Huge thanks!
