### ISSUE TITLE
Trying to get processor info gives me this error

### ISSUE THREAD

**Issue by joecharika** [oshi/oshi#842]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.sun.jna.Structure.toArray(Structure.java:1626)
	at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformation(Kernel32Util.java:675)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.calculateProcessorCounts(WindowsCentralProcessor.java:259)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:120)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:208)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getProcessor(WindowsHardwareAbstractionLayer.java:70)
	at filexplorer.XplorerPageController.getSystemInfo(XplorerPageController.java:93)
	at filexplorer.XplorerPageController.OpenSystemInfo(XplorerPageController.java:283)
	... 53 more

**Comment by dbwiddis** [comment]
This is a bug in JNA, already reported at https://github.com/java-native-access/jna/pull/1087 and fixed at https://github.com/java-native-access/jna/pull/1088 .  I'll update OSHI when the patch is released.

**Comment by dbwiddis** [comment]
Fixed in #845
